### ISSUE TITLE
Add specs for GitRepo module

### ISSUE THREAD

**Issue by jawshooah** [brigade/overcommit#156]
Currently, no specs exist for the `GitRepo` module, though a few of its methods are indirectly covered by the specs for the `PreCommit` and `PostCommit` `HookContext`s.

Writing specs for `GitRepo` would help to DRY up the aforementioned `HookContext` specs, but more importantly would provide some assurance that a substantial component of the core library works as intended.

**Comment by sds** [comment]
Added missing specs in cfc08ed...241ff62.
