### ISSUE TITLE
#setup_environment should store modification times for unstaged files

### ISSUE THREAD

**Issue by jawshooah** [brigade/overcommit#159]
Currently, `Overcommit::HookContext::PreCommit#setup_environment` only stores the modification times for staged files. If there are unstaged changes, their modification times will change when the stash is reapplied in `#cleanup_environment`.

This is not immediately apparent in the specs, since `#cleanup_environment` is run immediately after `#setup_environment`, and the elapsed time is much less than a second, which is the granularity `File.mtime` provides.

**Comment by sds** [comment]
Fixed by #172.
