### ISSUE TITLE
Any chance of bumping the version number soon?

### ISSUE THREAD

**Issue by mattcl** [brigade/overcommit#170]

**Comment by sds** [comment]
Yes, we're very anxious to release the next version of Overcommit. It'll have a lot of awesome new features to play with!

Right now, there are two issues that I'd like to get fixed before then:
* #159 
* #168 

#168 might be something we deem not important enough to block a release, but I haven't investigated it too deeply yet. 

We'll try to release by the end of this week.

**Comment by lencioni** [comment]
I've added these issues to a 0.24.0 milestone to make them a bit easier for you to track. https://github.com/brigade/overcommit/milestones/0.24.0

**Comment by mattcl** [comment]
Thanks!
