### ISSUE TITLE
Is the PryBinding hook necessary?

### ISSUE THREAD

**Issue by deivid-rodriguez** [brigade/overcommit#174]
It's already handled by RuboCop and if I want to disable it, I need to disable both the RuboCop cop and the PryBinding hook.

**Comment by sds** [comment]
I didn't realize `rubocop` had a cop which reported these sorts of issues when I merged the original pull request in #48. I've removed this hook in 00fba92238ad44d17a6a8575bc7bce62e57a8aac.

As discussed in https://github.com/brigade/overcommit/issues/122#issuecomment-87114806, starting with Overcommit 0.24.0 we'll be disabling almost all hooks by default, so this should no longer become an issue either way.

**Comment by deivid-rodriguez** [comment]
Thanks @sds !
