### ISSUE TITLE
RuboCop

### ISSUE THREAD

**Issue by bbatsov** [brigade/overcommit#198]
Just a tiny remark - Rubocop's officially written as RuboCop. :-) Fix or ignore this. I just wanted to mention it.

**Comment by sds** [comment]
Yeah, the name was changed after we had already written the hook. :)

Having said that, now's a good a time as any to rename it. Thanks for the reminder.

Renamed in 68a000f1e515ccabd4c7e9c69514bcc245054bf2

**Comment by bbatsov** [comment]
Thanks!

On 30 April 2015 at 08:51, Shane da Silva <notifications@github.com> wrote:

> Yeah, the name was changed after we had already written the hook. :)
>
> Having said that, now's a good a time as any to rename it. Thanks for the
> reminder.
>
> Renamed in 68a000f
> <https://github.com/brigade/overcommit/commit/68a000f1e515ccabd4c7e9c69514bcc245054bf2>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brigade/overcommit/issues/198#issuecomment-97669582>.
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com
