### ISSUE TITLE
Committing with an empty commit message causes all CommitMsg hooks to blow up

### ISSUE THREAD

**Issue by jfelchner** [brigade/overcommit#201]
Just like what it says.  The hooks should probably not fire and just let git handle the empty commit message.

**Comment by jfelchner** [comment]
The various errors:

```
Hook raised unexpected error
undefined method `[]' for nil:NilClass
```

```
Hook raised unexpected error
undefined method `length' for nil:NilClass
```

```
Hook raised unexpected error
undefined method `rstrip' for nil:NilClass
```

**Comment by sds** [comment]
Hey @jfelchner, thanks for the report!

1. We should definitely not crash here, so let's fix that.

2. We should add a hook that reports empty commit messages, as that seems like something you wouldn't want to ever do. I don't think we should not run `CommitMsg` hooks if there is no message; hooks should be written to support that case. Once #143 is implemented we can even have the built-in hooks depend on the hook that checks for empty commit messages so they don't need to check themselves.

**Comment by jfelchner** [comment]
@sds git already handles empty commit messages so no need to handle that in overcommit but whatever you think is best as long as it doesn't crash. :)

**Comment by sds** [comment]
@jfelchner Ah, I didn't actually try this. I see what you mean. Fair enough&mdash;we should just not crash. :)

**Comment by jawshooah** [comment]
Definitely a good idea to add a hook that checks for an empty message, though.
