### ISSUE TITLE
Breaking change in detached HEAD reporting in Git 2.4.0 

### ISSUE THREAD

**Issue by jawshooah** [brigade/overcommit#203]
The way Git reports a detached HEAD has [changed](https://github.com/git/git/blob/v2.4.0/Documentation/RelNotes/2.4.0.txt#L28) in 2.4.0. This breaks `GitRepo.branches_containing_commit`, which filters out a detached HEAD using a regex that is no longer accurate.

**Comment by sds** [comment]
Fixed by #205.
