### ISSUE TITLE
Prevent Inline styling (pre-commit hook)

### ISSUE THREAD

**Issue by pratik60** [brigade/overcommit#209]
Want to look in selective files (html, erb etc), and if it has inline styling it shouldn't go through. Any suggestions on how I could set this up? Custom Pre Commit hook which involves regex on any modified line?

**Comment by sds** [comment]
Hey @pratik60,

The beauty of Overcommit is that there's no real limitation to how you can solve a particular problem. I don't know of any general solutions for linting HTML at that level, but a regex-based solution would [probably not be advisable](http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454).

However, if you're looking for something that will probably work for most cases, looking for the string `style=` in your document is probably the easiest approach, since that is what I assume you mean by inline styling.

As the Overcommit project is merely a framework and tries not to hold any opinions about tools themselves, I would suggest you direct your question to [StackOverflow](http://stackoverflow.com/) to see what that community has to suggest. Thanks!

**Comment by pratik60** [comment]
@sds I wrote something but it didn't work

Its says undefined method modified lines
```
module Overcommit::Hook::PreCommit
  # Checks for trailing whitespace in files.
  class InlineStyle < Base
    # Overcommit expects you to override this method which will be called
    # everytime your pre-commit hook is run.
    def run
      # Create two arrays to hold our error and warning messages.
      error_lines = []
      warning_lines = []

      # For pre-commit hooks, `applicable_files` is one of the methods that
      # Overcommit provides which returns an array of files that have been
      # modified for the particular commit.
      applicable_files.each do |file|
        # `modified_lines` is another method provided by Overcommit. It will
        # return an array containing the index of lines in the file which have
        # been modified for the particular commit.
        modified_lines_num = modified_lines(file)

        # Loop through each file with the index.
        File.open(file, 'r').each_with_index do |line, index|
          # Check if the length of line is greater than our desired length.
          # If the line is included in our modified lines, we will add it to
          # `error_lines`, else add it to `warning_lines`.
          if line =~ /style="([^"]*)"/
            if modified_lines_num.include?(index + 1)
              error_lines << message
            else
              warning_lines << message
            end
          end
        end
      end

      # Overcommit expects 1 of the 3 as return values, `:fail`, `:warn` or `:pass`.
      # If the hook returns `:fail`, the commit will be aborted with our message
      # containing the errors.
      return :fail, error_lines.join("\n") if error_lines.any?

      # If the hook returns `:warn`, the commit will continue with our message
      # containing the warnings.
      return :warn, "Modified files have inline styling (on lines you didn't modify)\n" <<
        warning_lines.join("\n") if warning_lines.any?

      :pass
    end
  end
end
```

Any idea what's the new method to do this?

**Comment by jawshooah** [comment]
`modified_lines` was deprecated and eventually removed in favor of `modified_lines_in_file`. Try using that instead.

**Comment by pratik60** [comment]
@jawshooah @sds 

In case anyone is interested, here is the full code :-)

module Overcommit::Hook::PreCommit
  # Checks for trailing whitespace in files.
  class InlineStyle < Base
    # Overcommit expects you to override this method which will be called
    # everytime your pre-commit hook is run.
    def run
      # Create two arrays to hold our error and warning messages.
      error_lines = []
      warning_lines = []

      # For pre-commit hooks, `applicable_files` is one of the methods that
      # Overcommit provides which returns an array of files that have been
      # modified for the particular commit.
      applicable_files.each do |file|
        next unless File.extname(file) == '.erb'
        # `modified_lines` is another method provided by Overcommit. It will
        # return an array containing the index of lines in the file which have
        # been modified for the particular commit.
        modified_lines_num = modified_lines_in_file(file)

        # Loop through each file with the index.
        File.open(file, 'r').each_with_index do |line, index|
          # Check if the length of line is greater than our desired length.
          # If the line is included in our modified lines, we will add it to
          # `error_lines`, else add it to `warning_lines`.
          if line =~ /style="([^"]*)"/
            message = format("#{file}:#{index + 1}: Line has inline styling")
            if modified_lines_num.include?(index + 1)
              error_lines << message
            else
              warning_lines << message
            end
          end
        end
      end

      # Overcommit expects 1 of the 3 as return values, `:fail`, `:warn` or `:pass`.
      # If the hook returns `:fail`, the commit will be aborted with our message
      # containing the errors.
      return :fail, error_lines.join("\n") if error_lines.any?

      # If the hook returns `:warn`, the commit will continue with our message
      # containing the warnings.
      return :warn, "Modified files have inline styling (on lines you didn't modify)\n" <<
        warning_lines.join("\n") if warning_lines.any?

      :pass
    end
  end
end

**Comment by jawshooah** [comment]
Glad to see you got it working! :+1:
