### ISSUE TITLE
How to run my own hooks also?

### ISSUE THREAD

**Issue by skywinder** [brigade/overcommit#213]
How to run hooks, that now placed in `.git/hooks/old-hooks` ?

**Comment by jawshooah** [comment]
My understanding is that Overcommit is intended to replace your existing hooks, allowing you to duplicate their behavior with custom hooks within the framework.

**Comment by skywinder** [comment]
@jawshooah correct. But there is some several hooks, that hard to reimplement manually. (for example I use nice tool: https://github.com/mroth/lolcommits ) and it also put custom hook to this folder.

What about such enchantment:
Make an potion to durring installation not just move away existing scripts, but add execution of them as custom hook with `:pass` return. What do you think about this option? Is it possible to implement?

**Comment by jawshooah** [comment]
Well, you could add a custom hook that simply executes `.git/hooks/old-hooks/pre-commit` and handle the output and return code however you like.

**Comment by sds** [comment]
Hey @skywinder,

As @jawshooah mentions, the easiest way is to execute your script in the hook itself. See the [`GerritChangeId` `commit-msg`](https://github.com/brigade/overcommit/blob/master/lib/overcommit/hook/commit_msg/gerrit_change_id.rb) hook for an example.

**Comment by skywinder** [comment]
@jawshooah already did, thanks!
@sds :+1: thanks for awesome tool.
