### ISSUE TITLE
Disable "No applicable X hooks to run" message

### ISSUE THREAD

**Issue by olliebennett** [brigade/overcommit#230]
I often see the "No applicable <hook script name> hooks to run" messages, which are a little distracting when they regularly appear while working with git.

I see the `nothing_to_run` method is responsible for this, but I don't see any way to disable it.

I understand it's not a big issue, but is there an option or trick I could use to disable this?

To clarify, this is not a bug - I have none of these hook types configured.

Listing some examples below to improve searchability:
```
✓ No applicable post-checkout hooks to run
✓ No applicable pre-rebase hooks to run
✓ No applicable post-commit hooks to run
✓ No applicable post-rewrite hooks to run
✓ No applicable pre-push hooks to run
```

**Comment by jawshooah** [comment]
@sds perhaps we could tie this to #221 and only print these messages with verbose mode activated.

**Comment by sds** [comment]
This message is now output only in debug mode as of dd0af29.
