### ISSUE TITLE
Document the current capabilities and limitations of pre-commit hooks

### ISSUE THREAD

**Issue by grempe** [brigade/overcommit#237]
Referencing pull request: https://github.com/brigade/overcommit/pull/235#issuecomment-117379053

There is a lack of documentation regarding what pre-commit hooks (and probably others as well) can do as a result of implementation details of overcommit.

For example, pre-commit hooks implemented in overcommit cannot have side effects.  You cannot modify, add, remove files from within a pre-commit hook since the workflow for running that hook involves stashing all unindexed content in the work dir, doing a git reset --hard, and stash apply.  These actions overwrite any changes that a script might have made.

Currently this behavior is undocumented.

**Comment by grempe** [comment]
I referenced the wrong comment.  It should be:  https://github.com/brigade/overcommit/pull/235#issuecomment-117370907

**Comment by sds** [comment]
Added some documentation in 6c88cafc2cb0feea96c12a85437f4d770ab892fc.
