### ISSUE TITLE
problem_on_unmodified_line Clarification

### ISSUE THREAD

**Issue by sshaw** [brigade/overcommit#240]
The docs state:

> How to treat errors reported on lines that weren't modified during the action captured by this hook ...

Does this mean that erroneous code committed *prior* to the current commit will not cause it to fail when `problem_on_unmodified_line` is not set to `report`? Currently this is not the case with RuboCop. 

Code that is not part of the current commit causes RuboCop to issue offenses which result in the commit being rejected by the pre-commit hook.

**Comment by sds** [comment]
Hey @sshaw,

It would help if you included your `.overcommit.yml` and the file you are trying to commit. Remember that if you have `on_warn: fail` in your `RuboCop` hook configuration it will fail even if a warning is reported on a line you didn't change.

**Comment by sshaw** [comment]
Here you go. Note that RuboCop's output refers to lines that are not part of the current changes:

```
~/code/ruby/commerce-test-repo >cat .overcommit.yml
PreCommit:
  AuthorName:
    enabled: false

  RuboCop:
    enabled: true
    problem_on_unmodified_line: ignore

~/code/ruby/commerce-test-repo >git --no-pager diff bs.rb
diff --git a/bs.rb b/bs.rb
index e12d200..65b67f0 100644
--- a/bs.rb
+++ b/bs.rb
@@ -9,3 +9,6 @@ end

 bs = Bs.new
 p bs.test
+
+class Zee
+end

~/code/ruby/commerce-test-repo >overcommit --run
Running pre-commit hooks
Analyzing with RuboCop......................................[RuboCop] FAILED
Errors on modified lines:
/Users/sshaw/code/ruby/commerce-test-repo/bs.rb:1:6: C: Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
/Users/sshaw/code/ruby/commerce-test-repo/bs.rb:4:1: C: Style/Documentation: Missing top-level class documentation comment.
Warnings on modified lines:
/Users/sshaw/code/ruby/commerce-test-repo/bs.rb:1:1: W: Lint/UselessAssignment: Useless assignment to variable - `x`.
/Users/sshaw/code/ruby/commerce-test-repo/bs.rb:6:5: W: Lint/UselessAssignment: Useless assignment to variable - `x`.


✗ One or more pre-commit hooks failed
```

**Comment by sshaw** [comment]
Here's the output without `overcommit --run`:

```
~/code/ruby/commerce-test-repo >git add bs.rb
~/code/ruby/commerce-test-repo >git commit -m'testing...'
Running pre-commit hooks
Analyzing with RuboCop......................................[RuboCop] FAILED
Errors on modified lines:
/Users/sshaw/code/ruby/commerce-test-repo/bs.rb:1:6: C: Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
Warnings on modified lines:
/Users/sshaw/code/ruby/commerce-test-repo/bs.rb:1:1: W: Lint/UselessAssignment: Useless assignment to variable - `x`.


✗ One or more pre-commit hooks failed
```

**Comment by jawshooah** [comment]
It would help if you could run the check on a small dummy file and post both the entire file and the results of both `git commit` and `overcommit --run`.

**Comment by sshaw** [comment]
> It would help if you could run the check on a small dummy file and post both the entire file and the results of both git commit and overcommit --run.

With the exception of the dummy file's contents that's what I've done. Is there something you're expecting to see that isn't there? Cause that's it.

Here's the file I used, `bs.rb`:

```
~/code/ruby/commerce-test-repo >cat bs.rb
x  = "123"
X  = 999

class Bs
  def test
    x = 999
  end
end

bs = Bs.new
p bs.test

class Zee
end
```

**Comment by sshaw** [comment]
> Also note that overcommit --run treats all lines in all files as modified, as documented in the Usage and Continuous Integration sections of the README.

Yes, see: https://github.com/brigade/overcommit/issues/240#issuecomment-118168207

**Comment by sds** [comment]
When I try this locally it works as expected. It's likely that you haven't committed or staged the changes to your `.overcommit.yml` that include the `problem_on_unmodified_line: ignore` setting, meaning that setting won't take effect during the hook run.

What's the output of `git diff` for the scenario above? If `.overcommit.yml` has unstaged changes, that's probably the issue here.

**Comment by jawshooah** [comment]
Thanks @sshaw, I needed the file contents to see if I could duplicate the issue locally. Like @sds, everything works fine for me.

The strange bit is that you're seeing `Errors/Warnings on modified lines` instead of `Errors/Warnings on lines you didn't modify`. What do you get for `overcommit --version`?

**Comment by sshaw** [comment]
> When I try this locally it works as expected. 

I created a new repo and it did indeed work. The current repo has had many Overcommit related changes. It's my testbed.

> When I try this locally it works as expected. It's likely that you haven't committed or staged the changes to your .overcommit.yml...

Humm, there are changes, but as you can see I had already set `problem_on_unmodified_line` to `warn` so it should be in effect for this commit, which should still not result in a failure:

```
~/code/ruby/commerce-test-repo >git --no-pager diff
diff --git a/.overcommit.yml b/.overcommit.yml
index 5e0e267..357fd2d 100644
--- a/.overcommit.yml
+++ b/.overcommit.yml
@@ -12,23 +12,6 @@
 #
 # For a complete list of options that you can use to customize hooks, see:
 # https://github.com/brigade/overcommit#configuration
-#
-# Uncomment the following lines to make the configuration take effect.
-
-#PreCommit:
-#  RuboCop:
-#    on_warn: fail # Treat all warnings as failures
-#
-#  TrailingWhitespace:
-#    exclude:
-#      - '**/db/structure.sql' # Ignore trailing whitespace in generated files
-#
-#PostCheckout:
-#  ALL: # Special hook name that customizes all hooks of this type
-#   quiet: true # Change all post-checkout hooks to only display output on failure
-#
-#  IndexTags:
-#    enabled: true # Generate a tags file with `ctags` each time HEAD changes

 PreCommit:
   AuthorName:
@@ -36,7 +19,10 @@ PreCommit:

   RuboCop:
     enabled: true
-    #problem_on_unmodified_line: warn
+    problem_on_unmodified_line: ignore

   TrailingWhitespace:
+    enabled: true
+
+  YamlSyntax:
     enabled: true
\ No newline at end of file
``

> What do you get for overcommit --version
Running 0.26.0

Thanks for the help, guys. I'm excited to get this up and running on all of my team's projects.

**Comment by sshaw** [comment]
> I had already set problem_on_unmodified_line to warn

Ah wait! Warn was commented out, so the default would then be in effect which explains everything. Sorry for the confusion and thanks for the help!
