### ISSUE TITLE
Overcommit logo

### ISSUE THREAD

**Issue by lencioni** [brigade/overcommit#241]
I think it would be really great if overcommit had a better identity and I think that a good logo would go a long way. I figured I'd open this issue to collect ideas. I have some friends who have had reasonable luck using 99designs so something like that might be a reasonable option, but I think it would be best if it came from the community.

**Comment by sds** [comment]
In the interest of having _something_ to start a hopefully not-too-bikesheddy discussion, may I suggest:

<img width="1077" alt="overcommit-logo" src="https://cloud.githubusercontent.com/assets/677877/12987462/2e2b4aac-d0ca-11e5-8578-a0bc80b61d3f.png">

Font is [Adelle](https://typekit.com/fonts/adelle-web) and first "o" is from the [Git SCM documentation logo](https://git-scm.com/downloads/logos), which are licensed under Creative Commons Attribute 3.0, meaning they are free to modify as long as we credit the original author Jason Long.

The sizing here is funky but I currently lack the image editing software to do this correctly.

**Comment by jawshooah** [comment]
I like the idea, but to me it just reads as "vercommit". Maybe the Git logo should be circular? Same style, but looking more like an "O".

**Comment by sds** [comment]
Good point, the sharper edges don't mesh well with the curves of the rest of the font.

I think taking the "o" from "commit", filling it in, and sticking the git graph nodes from the Git logo would probably work here.

**Comment by lencioni** [comment]
This is great! I was thinking the same thing as @jawshooah and I think your idea about the "o" is perfect. @sds++ FTW!

**Comment by sds** [comment]
![screen shot 2016-02-12 at 12 23 28 am](https://cloud.githubusercontent.com/assets/677877/12999870/d1855bfa-d121-11e5-8863-b64519cbdaa2.png)

**Comment by lencioni** [comment]
Nailed it!

**Comment by jawshooah** [comment]
:+1:

**Comment by trotzig** [comment]
I hear Brigade is [looking for a Design Director](https://jobs.lever.co/brigade/d8a0166d-8d34-418f-822d-333e6531a7fa). :wink:
