### ISSUE TITLE
Add an overcommit hook for shellcheck

### ISSUE THREAD

**Issue by jfelchner** [brigade/overcommit#242]
This is just a placeholder.  I'd like to get to this, but if someone comes along behind me and is interested, I wanted a place to keep track of the discussion.

https://github.com/koalaman/shellcheck

**Comment by jfelchner** [comment]
Hahaha just realized this is already a thing.  It just had an extra space in it. `shell_check` vs the official `shellcheck`.

**Comment by sds** [comment]
Hey @jfelchner,

Not sure which `shell_check` spelling you're referring to, but since the tool is officially spelled "ShellCheck", we named the hook file `shell_check.rb` so that name would work with Ruby's naming conventions.

**Comment by jfelchner** [comment]
@sds yeah. No I see that now.  I was just looking at the package name and github repo name and not at how it was used in the README.  Thanks!
