### ISSUE TITLE
Locally installed gems fail the executable check

### ISSUE THREAD

**Issue by IanWhitney** [brigade/overcommit#243]
This may be a bug, or it may be me doing things the wrong way. But I wanted to document it here, as I didn't see it documented elsewhere, and because it might lead to a discussion that will help me learn about the best ways to use Overcommit.

I have a project with RuboCop in its Gemfile. We have Bundler configured to install gems locally, in `./bundle`. It also installs binstubs in `./bin`

After I `bundle` the project, `bundle exec rubocop` and `./bin/rubocop` work as expected: RuboCop runs and tells me to change my code.

The project's .overcommit.yml file is:

```yml
PreCommit:
  RuboCop:
    on_warn: fail
    enabled: true
    command: ['bundle', 'exec', 'rubocop']
```
Unlike RuboCop, we install Overcommit system wide. So I run `overcommit -r` and get

```
Running pre-commit hooks
Analyzing with RuboCop......................................[RuboCop] FAILED
'rubocop' is not installed (or is not in your PATH)
Install it by running: gem install rubocop

✗ One or more pre-commit hooks failed
```

The problem seems to be that the default configuration expects the rubocop executable to exist in my current $PATH. But with locally installed gems like this, it doesn't (well, unless I change my $PATH to allow `./bin`, which we don't do).

However, in the `command` config, I'm explicitly telling Overcommit how to call RuboCop -- `bundle exec rubocop`.  It seems like Overcommit is ignoring the `command` setting when its checking to see if the executable exists. But, it's entirely possible that I'm just doing something weird.

By the way, my fix for this was to add this line to our overcommit.yml 

```yml
required_executable: './bin/rubocop'
```

**Comment by jawshooah** [comment]
I believe your fix is the recommended way to handle this situation, as noted in [#211 (comment)](https://github.com/brigade/overcommit/issues/211#issuecomment-101415197).

**Comment by IanWhitney** [comment]
Thanks for the link, @jawshooah. I didn't spot that issue while searching.

Looking through the comments there, it seems like this functionality is not settled. I think one of two approaches makes sense

- Document the behavior more clearly in the docs
- Alter the code so that it behaves consistently

I'm interested in pitching in with either approach. A documentation PR is easy enough. But if the maintainers have a clear way they want this to work, I'm happy to try to implement that.

**Comment by sds** [comment]
Hey @IanWhitney, thanks for pointing out this potential source of confusion.

Can you elaborate on your second approach? I'm not sure what is "inconsistent" about the current behavior, so I'm curious what you think would make more sense.

With `required_executable`, you are declaring an executable that must be resolvable, and if it isn't the hook will fail. Like in any scripting shell (e.g. `bash`) if you specify an executable with no leading path prefix (e.g. just `rubocop`) it will search your `PATH` for the executable. If you specify it with a path prefix (e.g. `./bin/rubocop`) then it will use that exact executable relative to your current working directory. In Overcommit's case it will always be relative to the root of your repository.

Interested in hearing your thoughts.

**Comment by IanWhitney** [comment]
Yeah, my sentence wasn't very clear. Sorry about that. 

I think what I would expect to see is that if I specify a `command` then that would turn checking of `required executable`. This makes sense to me because, as I understand the `command` setting, I'm using it to tell Overcommit how to run the binary. So, if the binary doesn't exist it's totally my fault.

So, with the .overcommit.yml file like:

```yam
PreCommit:
  RuboCop:
    on_warn: fail
    enabled: true
    command: ['bundle', 'exec', 'rubocop']
```
Overcommit would see the command setting and assume that `bundle exec rubocop` works. It wouldn't even bother to check.

An alternative would be that Overcommit would ensure that `bundle exec rubocop` works, just like it does with `required_executable`. In this case the setting of `command` would override the setting of `required_executable`.

**Comment by sds** [comment]
I would disagree that setting the `command` is a strong signal that `required_executable` should be ignored. For example, there are some utilities (like `xargs`) that can be prepended to a command and enhance the functionality of the original command (e.g. executing chunks of arguments at a time in parallel). In this case, I still want to validate that the executable for the original utility can be found in my `PATH`.

With that said, I do agree we could do a better job of documenting this behavior, so I'll leave this issue open to track adding better documentation to the [Hook Options](https://github.com/brigade/overcommit#hook-options) section of the README.

**Comment by sds** [comment]
Attempted to clarify the behavior in de6f7f65581dfb211eb8f128c57f3b00570c1318.

**Comment by IanWhitney** [comment]
Thanks. We are really liking Overcommit. Excellent work.
