### ISSUE TITLE
Add pre-commit hook for puppet-lint

### ISSUE THREAD

**Issue by Mattias-** [brigade/overcommit#254]
It would be really cool to have something for puppet-lint :sunglasses: 

http://puppet-lint.com/

**Comment by sds** [comment]
Hey @Mattias-, thanks for the suggestion.

Given how simple it is to write hooks, I would encourage you to submit a pull request if you'd like to see this happen. :)

Check out pull request #178 for a simple example. Much of the code is boilerplate.

**Comment by sds** [comment]
...or you can have @jawshooah implement this for you. Nice timing on that one.

**Comment by jawshooah** [comment]
Sorry, was already working on it when I saw your comment!

**Comment by Mattias-** [comment]
Awesome guys! :trophy:
@sds My first option would have been to implement this myself but the arcane nature of RSpec stopped me from doing it immediately.

**Comment by jawshooah** [comment]
@Mattias- Even the hook specs are pretty standard at this point. You could just copy an [existing spec](https://github.com/brigade/overcommit/blob/master/spec/overcommit/hook/pre_commit/js_hint_spec.rb) and make a few modifications to the contexts and outputs as needed.
