### ISSUE TITLE
Add pre-commit hook to validate Nginx configs

### ISSUE THREAD

**Issue by jawshooah** [brigade/overcommit#255]
There's an [nginx-lint](https://github.com/temoto/nginx-lint) tool in development, but it's still in its infancy (9 commits in total) and relatively inactive (last commit was in January). Probably better to just use `nginx -t`.

**Comment by sds** [comment]
Nginx configuration files end with a pretty generic `.conf`. Certainly open a pull request, but this will become one of those hooks where developers will have to explicitly set the `include` option on the hook so it checks only the intended files.

**Comment by jawshooah** [comment]
Right, I was planning on setting the default to just `nginx.conf`, since that seems to match most of what I've seen.
