### ISSUE TITLE
Add pre-commit hook for hlint

### ISSUE THREAD

**Issue by jawshooah** [brigade/overcommit#260]
[hlint](https://github.com/ndmitchell/hlint) is a Haskell linting and code suggestion tool. Output looks something like this:

```sh
$ hlint --cross cross1.hs cross2.hs print.hs
print.hs:1:8: Error: Use print
Found:
  putStrLn $ show "Hello"
Why not:
  print "Hello"

cross1.hs:6:9: Warning: Reduce duplication
Found:
  a = 1
  b = 2
  c = 3

Why not:
  Combine with cross2.hs:5:9

2 suggestions
```

@sds How would you suggest we parse and display this kind of output? Should we only consider the first line of each suggestion, ignoring the "Found" and "Why not" stanzas?

**Comment by lencioni** [comment]
> How would you suggest we parse and display this kind of output? Should we only consider the first line of each suggestion, ignoring the "Found" and "Why not" stanzas?

I think that would be a great place to start. If it turns out that you need more information, you can always add it.

**Comment by jawshooah** [comment]
Makes sense to me. The user could always just run `hlint` manually to get the verbose output.
