### ISSUE TITLE
pre-commit hook jscs doesn't show any error message

### ISSUE THREAD

**Issue by xiaody** [brigade/overcommit#278]
Clone https://github.com/xiaody/overcommit-issue-demo and run `overcommit --run`
Output:
```
Running pre-commit hooks
Analyzing with JSCS............................................[Jscs] WARNING

⚠ All pre-commit hooks passed, but with warnings
```
No error message is shown.

But if I run `jscs *.js`,  jscs does output an error message.
```
One (or more) spaces required before opening brace for block expressions at error.js :
     1 |(function(){
-------------------^
     2 | 'add some trailing spaces in this line'
     3 |})


1 code style error found.
```

**Comment by xiaody** [comment]
It seems the exit value of jscs isn't correctly caught, and all warning || error cases go into https://github.com/brigade/overcommit/blob/v0.28.0/lib/overcommit/hook/pre_commit/jscs.rb#L13

**Comment by jawshooah** [comment]
Looks like they've changed their exit codes as of [this commit](https://github.com/jscs-dev/node-jscs/commit/6f8920da5fccba534ce69e51cad7b79731bbfe85). They're enumerated in the [wiki](https://github.com/jscs-dev/node-jscs/wiki/Exit-codes).

**Comment by jawshooah** [comment]
And apparently the documented exit codes are [incorrect](https://github.com/jscs-dev/node-jscs/issues/1800).

**Comment by sds** [comment]
Thanks for reporting this issue, @xiaody, and thanks for reporting the upstream issue, @jawshooah.

In response to https://github.com/jscs-dev/node-jscs/issues/1800, I've updated the `Jscs` hook to handle exit codes correctly in 311f73fc7ce2d7a63b5340a6aa9ba93bd446479a based on the documentation in `jscs`'s [wiki](https://github.com/jscs-dev/node-jscs/wiki/Exit-codes).
