### ISSUE TITLE
Scalastyle support

### ISSUE THREAD

**Issue by carymrobbins** [brigade/overcommit#282]
I assume I'm doing something wrong, but it seems that overcommit doesn't know how to use scalastyle.  I get this message when attempting to use it -

```
Analyzing with Scalastyle................................[Scalastyle] FAILED
'scalastyle' is not installed (or is not in your PATH)
```

The SBT plugin pulls it off using this jar -

```
~/.ivy2/cache/org.scalastyle/scalastyle_2.10/jars/scalastyle_2.10-0.7.0.jar
```

Assuming that wasn't good enough and that it was looking for a command line utility, I downloaded the [scalastyle-batch](http://www.scalastyle.org/command-line.html) jar from the scalastyle website and put it on my path.  Obviously, this wasn't going to be good enough, so I made a script called `scalastyle` and placed it on my path -

```bash
#!/bin/bash
java -jar $HOME/bin/scalastyle_2.10-0.6.0-batch.jar "$@"
```

And it seems to work as intended -

```
$ scalastyle -c scalastyle-config.xml path/to/src
warning file=/path/to/src/foo.scala message=File line length exceeds 100 characters line=117
Processed 2 file(s)
Found 0 errors
Found 1 warnings
Finished in 692 ms
```

Ok, so let's try it from the command line -

```
$ OVERCOMMIT_DEBUG=1 git commit -am foo
...
Analyzing with Scalastyle................................[Scalastyle] scalastyle ... (2 splittable args)
EXIT STATUS: 1
STDOUT: "scalastyle 0.6.0\nUsage: scalastyle [options] <source directory>\n -c, --config FILE               configuration file (required)\n -v, --verbose true|false        verbose output
\n -q, --quiet true|false          be quiet\n     --xmlOutput FILE            write checkstyle format output to this file\n     --xmlEncoding STRING        encoding to use for the xml fi
le\n     --inputEncoding STRING      encoding for the source files\n -w, --warnings true|false       fail if there are warnings\n"
STDERR: ""
OK
...
```

Ok, so, scalastyle exited with a non-zero status, and the commit hook passed.  I'm guessing it shouldn't.  Either way, seems I need to manually supply the `-c` argument, so I'll add that to the script with a hard-coded path to my config file.  Sure enough, it works!

```
$ OVERCOMMIT_DEBUG=1 git commit -am foo
Analyzing with Scalastyle................................[Scalastyle] scalastyle ... (2 splittable args)
EXIT STATUS: 0
STDOUT: "warning file=/path/to/src/foo.scala message=File line length exceeds 100 characters line=117\nProcessed 2 file(s)\n
Found 0 errors\nFound 1 warnings\nFinished in 704 ms\n"
STDERR: ""
WARNING
Warnings on modified lines:
warning file=/path/to/src/foo.scala message=File line length exceeds 100 characters line=117
```

Is there a better way to do this?  Also, should it be ignoring the non-zero exit status?

**Comment by jawshooah** [comment]
There are two problems here. The first is that you need to set `flags: ['-c', '{path to config file}']` in your `.overcommit.yml`. No need to hard-code it in your shim script.

The second is that we're ignoring a non-zero exit code if we can't find any error messages to parse. Notice that here, scalastyle just prints its version and usage, then exits.

The way the scalastyle hook is written now, it passes if there are no error messages to parse, regardless of exit code. I'll create a PR with a patch in a bit.

**Comment by jawshooah** [comment]
Also please notice that the hook options are [documented](https://github.com/brigade/overcommit#hook-options) in the README.

**Comment by matthewfarwell** [comment]
If this involves a change to the [doc for Scalastyle](http://www.scalastyle.org/git-pre-commit-hook.html), then can you submit a [PR for the doc](https://github.com/scalastyle/scalastyle.github.com/blob/master/git-pre-commit-hook.markdown). If not, can you close https://github.com/scalastyle/scalastyle/issues/162. Thanks.

**Comment by carymrobbins** [comment]
Thanks for the help!  I've submitted a PR to make the docs a bit more explicit about setting up scalastyle for overcommit.
