### ISSUE TITLE
Use regex to match branch names in `PrePush::ProtectedBranches` and `PreRebase::MergedCommits`

### ISSUE THREAD

**Issue by jawshooah** [brigade/overcommit#289]
Rather than having the user specify exact branch names, which is insufficient in cases where multiple permanent branches exist with similar names (e.g. `release/1.1.x`, `release/1.2.x`, etc), we should allow the user to specify a list of regexes (e.g. `release/.+`).

**Comment by jawshooah** [comment]
Note that this should be backwards compatible as long as we require that the regex match the *entire* branch name.

**Comment by sds** [comment]
Implemented in #316.
