### ISSUE TITLE
Possible contribution of PHP tools

### ISSUE THREAD

**Issue by craig-davis** [brigade/overcommit#292]
I have initial support for PHP linting via `php -l` and PHP code style checks via [phpcs](https://github.com/squizlabs/PHP_CodeSniffer). In the future, I plan to implement other tools from the [PHP QA Toolchain](http://phpqatools.org/).

Would you like a pull request for these initial hooks?

**Comment by lencioni** [comment]
Yes, absolutely we would. Please be sure to include specs and thanks for offering to help out!

**Comment by craig-davis** [comment]
Hi @lencioni - Where do you prefer that fixture files be located? I was expecting `spec/overcommit/fixtures` but don't see anything there.
