### ISSUE TITLE
Staged changes wiped while committing

### ISSUE THREAD

**Issue by JacobEvelyn** [brigade/overcommit#295]
I just committed and some overcommit checks failed, and then this happened:

```
✗ One or more pre-commit hooks failed

Unable to restore working tree after pre-commit hooks run:
STDOUT:
STDERR:fatal: Unable to create '/panorama/rainbow-backend/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
fatal: Unable to create '/panorama/rainbow-backend/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
Index was not unstashed.
```

I suspect this has to do with my oh-my-zsh theme, which resets the prompt every 10 seconds (because my prompt includes the `git status` if I'm in a git repository). My hunch is that at the time that the prompt reset, it executed a git command, obtaining the lock, which then stopped overcommit from being able to roll things back.

Pretty nasty issue; lost me quite a bit of work unfortunately.

**Comment by sds** [comment]
Hey @JacobEvelyn,

Your work should not be last. Check your stash: `git stash list` (notice in the message it says `Index was not unstashed.`). You should see a stash commit that Overcommit makes to protect against situations such as this.

Regarding this issue: yes, `git` is not safe to run concurrently within the same repository. I can understand why you might want to have your `git status` checked asynchronously, but as you can see this presents problems. It's surprising you never ran into it before, as this could technically hit you any time you run a `git` command.

I don't have any potential solution to offer, as this is a fundamental limitation of `git`, and I don't think it makes sense for Overcommit to try and detect that a `git` process is already running. I'm open to suggestions however.

**Comment by JacobEvelyn** [comment]
Thanks for the response, @sds. I actually have run into this occasionally where I'll run something like `git status` and get a git lock error, but this is the first time Overcommit's choked on it. You're right that the data was in fact in the stash.
