### ISSUE TITLE
Add pre-commit to check unix line feeds

### ISSUE THREAD

**Issue by senechaux** [brigade/overcommit#301]
It would be great to avoid carriage return chars (\r), the code would be the same as HardTabs pre-commit. I can prepare a Pull Request if you want to.

**Comment by sds** [comment]
One thing to keep in mind is that if your repository is ever developed on a Windows environment, then you'll need to provide some way for developers to work with carriage returns. Typically this is done with Git's `core.autocrlf` and `core.eol` options, but those aren't tracked in source control.

Given it's the same code as `HardTabs` (as you pointed out), we should probably create a generic hook that allows you to specify an arbitrary regex so you can flag any offensive lines. Then prohibiting carriage returns would be as simple as adding `\r$` to the regex, but we allow the hook to be used for other purposes as well (and stop polluting the namespace with a bunch of awfully simple hook names). 

Happy to accept a pull request.

**Comment by lencioni** [comment]
What if you want to exclude the hard tabs hook from some files but not
exclude the line feeds hook from those files?

**Comment by sds** [comment]
Good point, @lencioni. 

It sounds like we might want to re-introduce the idea of an [`inherit` option](https://github.com/brigade/overcommit/issues/139#issuecomment-85255956) so that we can define a canonical "grep" hook which can be inherited by other hooks to reuse that common code.

**Comment by senechaux** [comment]
At this point I think the best is to leave this idea and maybe create a place to link community custom hooks, what do you think?

**Comment by sds** [comment]
Overcommit itself includes a collection of built-in hooks which can be thought of as from the community.

I understand that you're suggesting something slightly different (and I'm definitely not against the idea), but I'm not personally interested in maintaining and moderating another collection besides the Overcommit's built-in hooks. I think the hooks that ship with Overcommit provide a nice collection of examples which others can copy/modify to suit their needs.
