### ISSUE TITLE
Configure colors

### ISSUE THREAD

**Issue by ilyakatz** [brigade/overcommit#308]
Currently, colors are hardcoded in the logger and with some color shemes it makes really hard to read overcommit messages.

Here is an example 

![image](https://cloud.githubusercontent.com/assets/282514/11788121/5fb90ad2-a25d-11e5-8b4b-b46dc0c57589.png)

**Comment by lencioni** [comment]
Where would the configuration for these colors live? If it was in the project's `.overcommit.yml` file it will apply to all people working on the project--who probably have different color schemes. It seems like we would need to make overcommit look in your home directory for this configuration or something in order to make this work.

**Comment by ilyakatz** [comment]
That is a good point. There are benefits to having an additional config (eg. as you suggested in home directory). I find that I have some hooks that are not used by other members of the team, so these could go here. Maybe that's a larger issue thoughu

**Comment by sds** [comment]
This typically isn't something I see command line applications supporting themselves. Two very large projects, [`rubocop`](https://github.com/bbatsov/rubocop) and [`eslint`](http://eslint.org/docs/user-guide/command-line-interface.html), for example, don't expose configuration to adjust colors. I'm sure there are some projects that do (would be curious to have some examples).

Typically, the onus is on the user using a custom terminal theme to choose appropriate colors to replace "yellow" and "red" colors that are suitable replacements for their given terminal theme.

I really don't like the idea of introducing a `.overcommit.yml.local` file or similar for specifying user-specific configuration, as the tool is intended to specify rules for _all_ developers of a project. I'm not convinced giving developers the power to tweak the configuration on an individual basis will serve a valuable purpose, and I think it will cause more confusion (developers will invariably forget about their local configurations and only consult their project configuration, in my experience).

**Comment by ilyakatz** [comment]
I don't think it's unusual to have individual developers set their own settings outside of the team's configurations (eg. bundler has `config` option). I guess this discussion just went beyond colors, but i still think it would be good to have a local configuration. i will understand if you're against it, maybe would be good to get feedback from others. your call onthis

**Comment by sds** [comment]
Right, I agree this is not unusual and makes a lot of sense for other tools. With bundler, for example, it totally makes sense that in a development environment you want to share gems with other projects you're developing, but in production you want to isolate yourself to only the project's gems by vendoring/isolating them to a directory.

My point is that the way I believe Overcommit should be used is to not allow individual developer configurations. The goal of the project is to make it easier to consistently enforce coding style/policies/habits for a project across an entire team. Given the key word there is "consistently", allowing developers to individually configure their experience is counter to this, as I see it.

I am open to hearing different viewpoints on the matter, but I'd like to hear some better use cases before straying from the idea of consistent configuration across all developers.
