### ISSUE TITLE
overcommit --sign not working?

### ISSUE THREAD

**Issue by thecristen** [brigade/overcommit#322]
I'm working with an existing repo on a new computer.

When I try to commit:
```
Unable to load configuration from ' (path omitted for brevity) /.overcommit.yml': No previously recorded signature for configuration file.
Run `overcommit --sign` if you trust the hooks in this repository.
```
While I get prompted to run `overcommit --sign`, running that actually throws a MissingArgument error.

When I run it with the relevant arguments, I get the 'No plugin signatures have changed' message. But I still can't commit.

**Comment by tdooner** [comment]
Hi @thecristen, sorry you're running into this bug. Overcommit's maintainer is out this week, but I can help you troubleshoot if you could paste the error message you get with `overcommit --sign` as well as the output of `overcommit --version`.

**Comment by jredburn** [comment]
I'm getting the same issue with `overcommit 0.28.0`:
```
overcommit --sign
/Users/jredburn/.rvm/gems/ruby-2.2.3/gems/overcommit-0.28.0/lib/overcommit/cli.rb:43:in `parse_arguments': missing argument: --sign (OptionParser::MissingArgument)
	from /Users/jredburn/.rvm/gems/ruby-2.2.3/gems/overcommit-0.28.0/lib/overcommit/cli.rb:18:in `run'
	from /Users/jredburn/.rvm/gems/ruby-2.2.3/gems/overcommit-0.28.0/bin/overcommit:7:in `<top (required)>'
	from /Users/jredburn/.rvm/gems/ruby-2.2.3/bin/overcommit:23:in `load'
	from /Users/jredburn/.rvm/gems/ruby-2.2.3/bin/overcommit:23:in `<main>'
	from /Users/jredburn/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jredburn/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jawshooah** [comment]
@jredburn Overcommit is on `0.30.0`. Do you still see the error after upgrading?

**Comment by jredburn** [comment]
Not sure what the underlying cause was, but was solved for me two ways:
- Deleting `.overcommit.yml`
- Upgrading to `0.30.0`

Thanks.

**Comment by jawshooah** [comment]
Well, deleting `.overcommit.yml` removes `overcommit` integration from your repository, so it makes sense that doing so would prevent `overcommit` errors from cropping up :wink:

**Comment by jredburn** [comment]
Heh fair enough.

**Comment by jawshooah** [comment]
Scratch that; default hook configurations remain in place after deleting `.overcommit.yml`. I'd actually expect `overcommit` to complain and ask you to `overcommit --sign` after making such a change. Weird.

**Comment by HarshitaJaiswal** [comment]
overcommit --sign
/home/hp/.rvm/gems/ruby-2.2.2/gems/overcommit-0.26.0/lib/overcommit/cli.rb:40:in `parse_arguments': missing argument: --sign (OptionParser::MissingArgument)
	from /home/hp/.rvm/gems/ruby-2.2.2/gems/overcommit-0.26.0/lib/overcommit/cli.rb:15:in `run'
	from /home/hp/.rvm/gems/ruby-2.2.2/gems/overcommit-0.26.0/bin/overcommit:8:in `<top (required)>'
	from /home/hp/.rvm/gems/ruby-2.2.2/bin/overcommit:23:in `load'
	from /home/hp/.rvm/gems/ruby-2.2.2/bin/overcommit:23:in `<main>'
	from /home/hp/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /home/hp/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'

overcommit version 0.26


Facing this error on running overcommit --sign .  Any suggestions will be appriciated

**Comment by sds** [comment]
Hey @HarshitaJaiswal, please upgrade to the latest version of overcommit (0.31.0 at time of writing).
