### ISSUE TITLE
GitGuilt default configuration incorrectly (?) sets requires_files: true

### ISSUE THREAD

**Issue by proinsias** [brigade/overcommit#326]
The default configuration in `default.yml` sets `requires_files: true` for GitGuilt, without any corresponding `include` files. I couldn't get this running initially until I set `requires_files: false`. I know that you could just specify `include` files in your `.overcommit.yml` file, but I just want this run on everything, which I assume would be a good default.

If I've interpreted this behavior correctly, I'm happy to submit a pull request.

**Comment by sds** [comment]
If `include` is not specified, the default is to check all modified files in the last commit. See https://github.com/brigade/overcommit/blob/v0.31.0/lib/overcommit/hook/base.rb#L156-L162 and https://github.com/brigade/overcommit/blob/v0.31.0/lib/overcommit/hook_context/post_commit.rb#L8-L11

I don't use the `GitGuilt` hook, so perhaps there's something I'm missing here with what you're describing. What you're describing sounds like a bug, unless you creating an empty commit.

**Comment by lencioni** [comment]
I recently successfully set up using `GitGuilt` with the following configuration

```yaml
PostCommit:
  GitGuilt:
    enabled: true
```

**Comment by proinsias** [comment]
Hmm. I am getting inconsistent results with different repositories. I'll have to investigate further.

**Comment by sds** [comment]
I'm going to close this given the lack of information here needed to reproduce.

Once you've got a working example, feel free to reopen!
