### ISSUE TITLE
Support for pre-commit hooks that modify the index

### ISSUE THREAD

**Issue by greenrd** [brigade/overcommit#330]
I attempted to write a pre-commit hook that modifies the index. When I set it as a CustomScript in my `.overcommit.yml`, it runs but it has no effect - and that's because overcommit stashes and recreates the previous state, so its changes are obliterated. So I had the idea of replacing the overcommit script with a script that calls my pre-commit script and then overcommit-hook, but overcommit-hook said:

    Don't run `overcommit-hook` directly; it is intended to be symlinked by each hook in a repository's .git/hooks directory.

**Comment by greenrd** [comment]
A workaround is to rename the overcommit pre-commit symlink to `preCommit` and then call that from my script. Perhaps this workaround should be documented.

(I also tried `exec -a $0` to set `$0`, but that didn't work.)

**Comment by sds** [comment]
Hey @greenrd,

I understand the desire to modify the index as part of a hook run, but this simply [isn't supported yet](https://github.com/brigade/overcommit/tree/v0.31.0#warning-pre-commit-hooks-cannot-have-side-effects). There is an open issue tracking this at #238.
