### ISSUE TITLE
overcommit requires 'bundle exec git ...' !?

### ISSUE THREAD

**Issue by sleekweasel** [brigade/overcommit#350]
$ which overcommit
    /Users/tim/.rvm/gems/ruby-2.1.5/bin/overcommit
    $ overcommit --version
    overcommit 0.31.0
    $ git push
    Unable to load configuration from '/Users/tim/git/bma-calabash3/.overcommit.yml': Signature of configuration file has changed!
    Run `overcommit --sign` once you've verified the configuration changes.
    error: failed to push some refs to 'git@git.mlan:bma-calabash.git'
    $ overcommit --sign
    Updating signature for configuration file...
    $ git push
    Unable to load configuration from '/Users/tim/git/bma-calabash3/.overcommit.yml': Signature of configuration file has changed!
    Run `overcommit --sign` once you've verified the configuration changes.
    error: failed to push some refs to 'git@git.mlan:bma-calabash.git'

Yet...

    $ bundle exec overcommit --version
    overcommit 0.31.0
    $ bundle exec git push
    Everything up-to-date

With debug, --sign doesn't seem to change anything:

    $ OVERCOMMIT_DEBUG=1 git checkout -- Gemfile.lock
    git rev-parse --git-dir
    EXIT STATUS: 0
    STDOUT: ".git\n"
    STDERR: ""
    git config --local --get overcommit.configuration.signature
    EXIT STATUS: 0
    STDOUT: "f443dab288028995d79855f9dd1ea00df4841587414c07d6f1a411b1c9f5ad85\n"
    STDERR: ""
    git config --local --get overcommit.configuration.signature
    EXIT STATUS: 0
    STDOUT: "f443dab288028995d79855f9dd1ea00df4841587414c07d6f1a411b1c9f5ad85\n"
    STDERR: ""
    Unable to load configuration from '/Users/tim/git/bma-calabash3/.overcommit.yml': Signature of configuration file has changed!
    Run `overcommit --sign` once you've verified the configuration changes.

and

    $ OVERCOMMIT_DEBUG=1 overcommit --sign
    Updating signature for configuration file...
    git config --local overcommit.configuration.signature f443dab288028995d79855f9dd1ea00df4841587414c07d6f1a411b1c9f5ad85
    EXIT STATUS: 0
    STDOUT: ""
    STDERR: ""
    git config --local overcommit.configuration.verifysignatures 1
    EXIT STATUS: 0
    STDOUT: ""
    STDERR: ""
    $

If it doesn't change anything, perhaps it should mention that?

I'm guessing that some other project I was working on had overcommit 0.32.0 installed, and maybe I ran a git command for this project from that one (!?) because updating this project to 0.32.0 seems to have fixed it. But it's a very frustrating and obscure solution, and I won't always be able to change that in a project.

Perhaps the signature should include information about which version of overcommit wrote it, or something?

**Comment by Jwan622** [comment]
Thanks for this!
