### ISSUE TITLE
Add option to hide verbose progress output

### ISSUE THREAD

**Issue by m1foley** [brigade/overcommit#357]
Despite setting `quiet: true` for all my hooks, I still see output like this:

```
Running pre-commit hooks

✓ All pre-commit hooks passed

Running commit-msg hooks

✓ All commit-msg hooks passed
```

I only want to see `overcommit` output if errors or warnings are present. This is how other Git hooks work, including `pre-commit` and `fit-commit`.

Some ideas on implementation:
- `log_level` global setting. Users who only want to see exceptional output can change this from `info` to `warn` or `error`.
- `verbose_progress` global setting. Users who only want to see exceptional output will change this from `true` to `false`.
- Output all progress updates to the `debug` log level.
- If `quiet: true` is enabled for a hook, don't output its progress.

**Comment by sds** [comment]
I agree that if developers explicitly choose to silence the hook output, they should be allowed to do that.

I think a simple top-level option `quiet` will suffice in this case. Introducing logging as a concept seems unnecessary given the use case being described here.

Happy to accept a pull request!
