### ISSUE TITLE
Brakeman not showing reports

### ISSUE THREAD

**Issue by abhilash1985** [brigade/overcommit#362]
Rails/Ruby version - rails 5 beta, ruby 2.3.0

I've added below configuration in .overcommit.yml

Brakeman:
    enabled: true
    description: 'Check for security vulnerabilities'
    required_executable: 'brakeman'
    flags: ['--exit-on-warn', '--quiet', '--only-files']
    install_command: 'gem install brakeman'
    include:
      - '**/*.rb'

But it returns like this

Check for security vulnerabilities.........................[Brakeman] FAILED
Analyze with RuboCop........................................[RuboCop] FAILED
Errors on modified lines:

Only brakeman not showing any line number or file description where exactly the security vulnerabilities happened. Please help.

**Comment by sds** [comment]
Hey @abhilash1985,

Don't change the `Brakeman` configuration unless you know what you are doing. In your example, you removed the `--summary` flag from the `flags` option.

All you should need to enable Brakeman in your Overcommit configuration is to enable it like so:

```yaml
PreCommit:
  Brakeman:
    enabled: true
```

Hope that helps.
