### ISSUE TITLE
CoffeLint not working as expected for modified line

### ISSUE THREAD

**Issue by amree** [brigade/overcommit#364]
Apparently coffelint will return as Passed even though it shouldn't

Overcommit config:

```
CoffeeLint:
  enabled: true
  on_warn: fail
  problem_on_unmodified_line: ignore
  command: ["coffeelint", "-f", "../../configs/coffeescript.json"]
```

Debug error message:

```
STDERR: ""
EXIT STATUS: 0
STDOUT: "path,lineNumber,lineNumberEnd,level,message\nfile.js.coffee,15,,warn,Colon assignment without proper spacing Incorrect spacing around column 17.\nExpected left: 0, right: 1.\nGot left: 3, right: 1..\nfile.js.coffee,16,,warn,Colon assignment without proper spacing Incorrect spacing around column 19.\nExpected left: 0, right: 1.\nGot left: 3, right: 1..\nfile.js.coffee,17,,warn,Colon assignment without proper spacing Incorrect spacing around column 17.\nExpected left: 0, right: 1.\nGot left: 5, right: 1..\nfile.js.coffee,18,,warn,Colon assignment without proper spacing Incorrect spacing around column 17.\nExpected left: 0, right: 1.\nGot left: 1, right: 1..\nfile.js.coffee,19,,warn,Colon assignment without proper spacing Incorrect spacing around column 17.\nExpected left: 0, right: 1.\nGot left: 2, right: 1..\nfile.js.coffee,25,,warn,Empty parameter list is forbidden\n"
STDERR: ""
Analyze with coffeelint..................................[CoffeeLint] OK

✓ All pre-commit hooks passed
```

I did some digging and found out that https://github.com/brigade/overcommit/blob/master/lib/overcommit/hook/pre_commit/coffee_lint.rb#L25 will return `String` for the line number and overcommit expect it to be `Fixnum` when it's doing comparison https://github.com/brigade/overcommit/blob/master/lib/overcommit/message_processor.rb#L145

I can send a pull request if you guys OK with it. I'll just convert it to `Fixnum`

**Comment by sds** [comment]
Thanks for catching this, @amree.

I'm not sure why `CoffeeLint` implements its own message parsing solution when we have the `extract_messages` helper (which handles the conversion for you). Perhaps while you're at it you could switch it to use the helper?

If not, a simple `.to_i` on `line` would also suffice. Thanks!

**Comment by jawshooah** [comment]
The reason is that we're using coffeelint's CSV formatter, which, while easy to parse, is not very human readable. Simply using `extract_messages` would print out the messages as they are reported, so instead we create new messages in a more readable format.
