### ISSUE TITLE
Overcommit hook supplants Git-Lfs hook, thereby breaking Git-Lfs

### ISSUE THREAD

**Issue by alexagranov** [brigade/overcommit#367]
After running `overcommit --install`, if `git-lfs` was previously installed, it's pre_push hook is moved to `.git/hooks/old_hooks` directory.  This breaks usage of Git-Lfs.

I've put together a custom PrePush hook named GitLfs that re-adds the Git-Lfs functionality, available as a [gist](https://gist.github.com/alexagranov/5492bbd8bf5d6f5869c232b1127cd4a4).

I'm not sure if this should be a Feature Request in this project to add a `template_dir/sample_hooks/` directory or something to that effect, or possibly an addition to Git-Lfs project.

**Comment by jawshooah** [comment]
You could just submit a pull request with your hook, we'd be happy to review it.

I don't think it will work as you expect right now, since shelling out to `git lfs pre-push` with backticks will swallow any errors and not prevent a push.

**Comment by alexagranov** [comment]
Will do.  And yeah, thought about that as I was getting this ready but decided to hear what the direction was first.  Won't be able to get to that until tomorrow.  Thanks.

**Comment by alexagranov** [comment]
Submitted PR #369

**Comment by jawshooah** [comment]
Solution in [#369 (comment)](https://github.com/brigade/overcommit/pull/369#issuecomment-212193259) should take care of this. Feel free to reopen if you have any trouble.
