### ISSUE TITLE
JSCS No Longer has --verbose Option

### ISSUE THREAD

**Issue by thegranddesign** [brigade/overcommit#374]
Hey all, JSCS v3 removed the `verbose` option and it's now the default.  This is causing that hook to fail.

![image](https://cloud.githubusercontent.com/assets/17790097/14932231/eb5aa2e8-0e38-11e6-87cc-08105bf6f6a6.png)

**Comment by sds** [comment]
Thanks for the report!

Fixed in f31c8ef.
