### ISSUE TITLE
Rebasing when commits include changes to .overcommit.yml breaks

### ISSUE THREAD

**Issue by thegranddesign** [brigade/overcommit#375]
I'm using the `--sign` feature, which I love most of the time, but it's pretty brutal when rebasing if the commits being rebased over contain changes to the `.overcommit.yml`.  This is because each rebased commit runs within the working tree of the commit being executed.  Therefore when a rebase is on a commit with a different `.overcommit.yml` file than the one that was signed, it fails spectacularly.

Not only is it a problem that it fails, but it doesn't even reset the state back to the way it was before the rebase started (moreover no rebase is in progress so you can't even `git rebase --abort`).

My proposal is that, when `overcommit --sign` is called, overcommit should copy the currently signed `.overcommit.yml` to the hooks directory such that changes to the working tree don't affect which config is being used.

If, during a commit, overcommit sees that the config file is different than the saved version, _and_ it's in the process of rebasing, it ignores the one in the working directory and uses the stored one instead.

**Comment by sds** [comment]
Hey @thegranddesign, thanks for the feedback.

I believe #300 would solve most of the pain you are referring to, unless you are referring to the case where you are rebasing onto changes which you have never signed before.

I would love to merge a pull request solving #300 or this issue. Fixing #300 would probably be easier from an implementation standpoint.

**Comment by thegranddesign** [comment]
@sds I'm not sure if I am or not. 😂 But I'll try `OVERCOMMIT_DISABLE` and see if that solves my problem. Thanks!
