### ISSUE TITLE
Commit Subject Capitalization Check Should Ignore Standard Git Rebase Prefixes

### ISSUE THREAD

**Issue by thegranddesign** [brigade/overcommit#377]
git has some standard prefixes for commit messages which allow interactive rebases to automatically sort commits:

* `fixup!`
* `squash!`

![image](https://cloud.githubusercontent.com/assets/17790097/14940417/d85aefb6-0f39-11e6-9d76-485ba5b4b985.png)

The subject capitalization check shouldn't throw a warning if either of these prefixes exist in the commit message since they are put there purposefully..

**Comment by sds** [comment]
Thanks for the suggestion, @thegranddesign.

Fixed in a46dcf20d105092b6f73acddfcef7c701c445b22.

**Comment by thegranddesign** [comment]
Thanks!!
