### ISSUE TITLE
Problem running overcommit "Unable to load configuration from '/home/greg/Work/.overcommit.yml': Signature of configuration file has changed!

### ISSUE THREAD

**Issue by pawlik** [brigade/overcommit#385]
```
$ overcommit --version
overcommit 0.32.0
$ overcommit --install     
Installing hooks into /home/greg/Work/
Successfully installed hooks into /home/greg/Work/
$ overcommit --sign      
Updating signature for configuration file...
$ git commit --amend     
Hooks updated to Overcommit version 0.33.0
Unable to load configuration from '/home/greg/Work/.overcommit.yml': Signature of configuration file has changed!
Run `overcommit --sign` once you've verified the configuration changes.
$ overcommit --sign    
Updating signature for configuration file...
$ git commit --amend   
Unable to load configuration from '/home/greg/Work/.overcommit.yml': Signature of configuration file has changed!
Run `overcommit --sign` once you've verified the configuration changes.
```
Please let me know how can I help with debugging this. 

The weird thing is information about hooks being updated to version `0.33.0`, but overcommit is in `0.32.0`

**Comment by sds** [comment]
The issue here is that the configuration is changing as part of the commit (the output you provide suggests this given the version changed).

Overcommit doesn't currently handle this situation well. #300 tracks the ideal solution, but for now the easiest approach is to run `OVERCOMMIT_DISABLE=1 git commit --amend`.

Hope that helps!

**Comment by pawlik** [comment]
I'm not sure what's your suggestion. I made one commit with disabled overcommit but all the subsequent commits result in the same error. Am I doing something wrong?

**Comment by sds** [comment]
Did you sign with `overcommit --sign` after making your commit? For example:

```
OVERCOMMIT_DISABLE=1 git commit --amend
overcommit --sign
```

Also, make sure you don't have any unstaged changes to your `.overcommit.yml`! (i.e. `git add .overcommit.yml` to stage all changes, otherwise when you commit the pre-commit hook will stash the unstaged changes resulting in the signature of your configuration changing again).

**Comment by pawlik** [comment]
> Did you sign with overcommit --sign after making your commit?

yes: 

```
$ OVERCOMMIT_DISABLE=1 git commit --amend
[fake-branch 56bb2ee] test
 Date: Thu Jun 9 10:52:18 2016 +0200
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test
$ overcommit --sign
Updating signature for configuration file...
$ git commit --amend
Hooks updated to Overcommit version 0.33.0
Unable to load configuration from '/home/greg/Work/.overcommit.yml': Signature of configuration file has changed!
Run `overcommit --sign` once you've verified the configuration changes.
```

Regarding the second part: `.overcommit.yml` is not tracked by git - it's ignored in `.gitignore` file. So it's definitely not stashed.

**Comment by sds** [comment]
Sorry for the delay in response, @pawlik.

I'm not sure what's going on here, but the fact that your `.overcommit.yml` isn't tracked by Git might be to blame. It's not the way to tool was designed (i.e. it was never expected someone would use Overcommit without committing their `.overcommit.yml`).

If you could provide a public repository where this behavior can be reliably reproduced, I'd be happy to investigate! Thanks!

**Comment by pawlik** [comment]
@sds I got it - I had installed it with `gem install overcommit` (`0.32.0`) and also in `Gemfile` (`0.33.0` arrived from repo), so the issue was config version mismatch. Thanks for you assistance.

**Comment by lehn-etracker** [comment]
I had the same problem here. Overcommit should warn, if configuration version != executable version
