### ISSUE TITLE
add info why it is better than https://github.com/pre-commit/pre-commit

### ISSUE THREAD

**Issue by matkoniecz** [brigade/overcommit#392]
It seems a very similar project and it is no obvious whetever one is better/for different purposes.

It would be nice to mention documentaton for what purposes this project is better

**Comment by sds** [comment]
The difference is quite clear from the the first line of each project's README:

Overcommit: 
> `overcommit` is a tool to manage and configure Git hooks.

pre-commit:
> A framework for managing and maintaining multi-language **pre-commit** hooks.

Overcommit is a more general solution. The pre-commit project deals with _only_ pre-commit hooks. That is the difference.

Whether one is "better" than the other is up to you. If you want to manage more than just pre-commit hooks, Overcommit provides greater flexibility in this regard.

Hope that helps!
