### ISSUE TITLE
Add LESS linter pre-commit hook

### ISSUE THREAD

**Issue by Friend-LGA** [brigade/overcommit#394]
Why did you forget about LESS?

[Here](http://lesscss.org/usage/#command-line-usage-options) documentation about LESS lint

**Comment by jawshooah** [comment]
If it's not here, it's only because nobody has submitted a PR to add it yet. You're welcome to take a crack at it and submit a PR yourself :smile:

**Comment by Ruffeng** [comment]
Would you go for a Less Linter? Or do you think is good to add stylelint, which can cover different formats?

**Comment by Ruffeng** [comment]
https://github.com/brigade/overcommit/pull/521
Someone already did a PR

**Comment by leblangi** [comment]
Stylelint is in the list and support less. I think we can close this issue :)
