### ISSUE TITLE
JavaCheckstyle should categorize 'warning' messages correctly

### ISSUE THREAD

**Issue by gautamjain** [brigade/overcommit#395]
Checkstyle tags messages (as `INFO`, `WARN`, and `ERROR`) depending on their severity.  However, Overcommit currently treats all messages as an error.  

Will submit a pull request to update this as discussed in
https://github.com/brigade/overcommit/issues/358#issuecomment-204184629

**Comment by Structon** [comment]
Please opt me out of this threat for I am not interested any more

thank you in advance

**Comment by lencioni** [comment]
@Structon it looks like you have chosen to "Watch" this project in the GitHub UI. The best way to prevent future notifications like the one you received for this thread is to remove yourself from the watchers by signing into your GitHub account and changing your watching status from "Watching" to "Not watching".

![screen shot 2016-07-01 at 3 22 24 pm](https://cloud.githubusercontent.com/assets/195534/16535839/af105178-3f9f-11e6-9ba4-9282c4f9d604.png)

I will delete your comment and this one as well to keep this issue clean.

**Comment by Structon** [comment]
OK thank you.

**Comment by sds** [comment]
Implemented in #396. Thanks!
