### ISSUE TITLE
RuboCop severity level

### ISSUE THREAD

**Issue by 73** [brigade/overcommit#399]
Hi Guys,

I'm using RuboCop with overcommit. When I run rubocop manually I see errors on "conventions" level, but the commit still passes overcommit. It works fine with warnings though.

It there a setting I did no see to enable errors on that level?

Best regards,
-- 73

**Comment by sds** [comment]
Hey @73,

It's hard to offer advice from the description you've provided. If you provided a list of steps with a public repo it would be much easier to tell you what's going on.

My initial thoughts are that you aren't running Overcommit within a [Bundler context](https://github.com/brigade/overcommit#gemfile), so you end up using different version of RuboCop when running `rubocop` manually versus when running via your hooks.

Hope that helps!
