### ISSUE TITLE
Using with GitX?

### ISSUE THREAD

**Issue by edelgado** [brigade/overcommit#401]
Has anyone had any luck using [GitX](https://rowanj.github.io/gitx/) with Overcommit? Even with the gem installed, I get these weird failures:

<img width="533" alt="screenshot 2016-07-18 16 19 35" src="https://cloud.githubusercontent.com/assets/143209/16930898/d550fd12-4d03-11e6-9ab2-d98a5f913b6d.png">

Note that the gem _is_ installed. Any ideas? This affects more than just GitX, basically any GUI for Git.

**Comment by edelgado** [comment]
Well I had to install this gem in the system Ruby by disabling `rbenv` and doing the ugly `sudo gem install overcommit` command. But works.

**Comment by sds** [comment]
Hey @edelgado, thanks for raising this issue and for sharing a workaround.

I don't use GitX but the likely reason it requires you to use the system Ruby is that it does not load the correct environment (i.e. `eval $(rbenv init -)`, which is likely in your `.bashrc`/`.zshrc` or similar).

I'm not familiar with obvious workarounds to those problems, but if someone knows of any please share!

**Comment by sds** [comment]
See [my answer](https://github.com/brigade/overcommit/issues/402#issuecomment-233492637) to a similar question which may be useful to others running into this issue.
