### ISSUE TITLE
All `flags` options break hook

### ISSUE THREAD

**Issue by agilgur5** [brigade/overcommit#411]
Not sure what's going on here, but every time I add a `flags:` option, the hook performs unexpectedly in some way -- though the errors all seem unrelated to each other (might need to separate out this issue). The 3 hooks I'm using `flags` in are `RuboCop`, `PythonFlake8`, and `Standard`.

For `RuboCop`, my config looks like:
```
RuboCop:
    enabled: true
    include: '**/Vagrantfile'
    flags: ['--except AlignParameters']
```

Output of `overcommit --run`:
```
Unexpected output: unable to determine line number or type of error/warning for output:
/var/lib/gems/1.9.1/gems/rubocop-0.41.2/lib/rubocop/options.rb:20:in `parse'
/var/lib/gems/1.9.1/gems/rubocop-0.41.2/lib/rubocop/cli.rb:24:in `run'
/var/lib/gems/1.9.1/gems/rubocop-0.41.2/bin/rubocop:14:in `block in <top (required)>'
/usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/var/lib/gems/1.9.1/gems/rubocop-0.41.2/bin/rubocop:13:in `<top (required)>'
/usr/local/bin/rubocop:23:in `load'
/usr/local/bin/rubocop:23:in `<main>'
```
If I remove the `flags` option, it runs fine. Running
`rubocop --except AlignParameters '**/Vagrantfile'` directly also runs as expected. Specifically for `RuboCop`, I've noticed that if I use the default overcommit flags as my `flags`, it runs fine. Adding `--except AlignParameters` to the array of defaults gives the same error as above.

For `PythonFlake8`, my config looks like:
```
  PythonFlake8:
    enabled: true
    include: '**/*.py'
    flags: [
      # default ignores + E128
      '--ignore E121,E123,E126,E226,E24,E704,W503,E128',
      '--exclude migrations/'
    ]
```

Output of `overcommit --run`:
`Analyze with flake8....................................[PythonFlake8] OK` (it doesn't seem to run at all).
If I remove the `flags`, it runs fine. Running
`flake8 --ignore E121,E123,E126,E226,E24,E704,W503,E128 --exclude migrations/ '**/*.py'` directly also runs as expected.

For `Standard`, my config looks like:
```
  Standard:
    enabled: true
    include: '**/*.es6'
    flags: ['--parser babel-eslint']
```

Output of `overcommit --run` is an error given using the standard parser, it doesn't use `babel-eslint` even though the `flags` option is so configured (it seems to be ignoring the flags option). Running `standard --parser babel-eslint '**/*.es6'` directly runs as expected.

No idea what the root cause is in all of these issues, but they're all linked by the fact that `flags` does not seem to work as intended.

**Comment by sds** [comment]
Hey @agilgur5,

These flags are passed directly to the OS to be processed as arguments.

Thus you must separate them into separate items in your list.

For example:

```yaml
  PythonFlake8:
    ...
    flags: [
      '--ignore', 'E121,E123,E126,E226,E24,E704,W503,E128',
      '--exclude', 'migrations/'
    ]
```

If you don't separate them out, then the entire element is passed as a single argument, which is not what you want!

Hope that helps.

**Comment by agilgur5** [comment]
Ohhh, of course it would be a really simple mistake; was really baffled by the output for a good hour and a half.

Thanks for the super fast response @sds!

**Comment by jawshooah** [comment]
@agilgur5 Fancy seeing you here!

**Comment by agilgur5** [comment]
oh hey @jawshooah! I think I actually learned of Overcommit a few years back after looking at your GitHub haha. Have been using for the past few months now, first time I screwed up some config though!
