### ISSUE TITLE
Add TSLint pre-commit hook

### ISSUE THREAD

**Issue by jhuiting** [brigade/overcommit#419]
> TSLint checks your TypeScript code for readability, maintainability, and functionality errors.
[http://palantir.github.io/tslint/](http://palantir.github.io/tslint/)

I'd like to have this hook in Overcommit, to provide similar functionality for TypeScript as we already have for JavaScript with ESLint. I'm willing to contribute this plugin, already started implementing this.

**Comment by sds** [comment]
Implemented in #421

**Comment by jhuiting** [comment]
Just realised that the hook is not listed yet in the documentation. I'll create a new PR to fix that.

**Comment by lencioni** [comment]
I wonder if we should add a repo pre-commit hook that ensures that rules are listed in documentation?

**Comment by jawshooah** [comment]
Whoops, sorry about that!

**Comment by jhuiting** [comment]
@lencioni A [Pull Request template](https://github.com/blog/2111-issue-and-pull-request-templates) is maybe even easier to start with
