### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by jclif** [brigade/overcommit#430]
During the installation steps, it was not obvious to me at first how to proceed from `overcommit --install`. I tried to run overcommit and it produced the following error:
```
/path/to/overcommit/configuration_loader.rb:81:in `verify_signatures': Unable to load configuration from '/Users/jclifton/Code/xogroup/thebump-web/.overcommit.yml': No previously recorded signature for configuration file. (Overcommit::Exceptions::ConfigurationError)
Run `overcommit --sign` if you trust the hooks in this repository.
```
The next step is fairly obvious, but it would be nice if it were explicitly outlined in the documentation in terms of getting started.

At any rate, thanks for the awesome software!

**Comment by sds** [comment]
Thanks for the feedback, @jclif. You're right that this can be a bit surprising.

Added documentation to the installation instructions in 57a1614.
