### ISSUE TITLE
Possible for unique .overcommit.yml file for different dev environments?

### ISSUE THREAD

**Issue by binarymason** [brigade/overcommit#435]
I have a script that logs how many commits I make in a day.  Is there a way to use inheritance with overcommit so I can create my own supplemental overcommit file that I can `gitignore`?  

Including this script in the `.overcommit.yml` file that the entire team uses doesn't make sense.

**Comment by sds** [comment]
Hey @binarymason, 

I totally understand the desire to have a "user-specific" Overcommit configuration, but I hope it's understandable why this isn't desirable. A major selling point (and intended purpose) of Overcommit is to provide a tool to consistently enforce policies via Git hooks across all members of your team. While your case seems innocuous, allow developers to "override" the settings with their local configuration that isn't checked in to source control seems wrong to me.

However, there are always ways around this, even if we don't want to support user-specific configurations as first class citizens, you add a custom Overcommit hook to your repository that checks for the existence of a script (whether it's in your home directory or wherever), and if it exists execute it. I think that is a pretty easy way to get what you want done, and it allows your team to "endorse" the use of these custom hooks by explicitly creating a hook to run said custom hooks.

If you're _really_ interested in adding support for this, I won't say no to a well-tested pull request! But I fear that the current code makes some pretty explicit assumptions that all configuration exists in the repository's top-level directory.

**Comment by binarymason** [comment]
hey @sds,

Thanks for the response.  The intention of having consistent "policies" makes sense.  I'm going to close this issue since it's out of alignment with Overcommit priorities.

In the meantime, I will look into your suggestion of adding a custom script in VCS that executes another script if it exists.

Thanks again!
