### ISSUE TITLE
Enforce license headers in source 

### ISSUE THREAD

**Issue by sectioneight** [brigade/overcommit#438]
I'd like to use overcommit to enforce license headers are present in source files. 

I don't see any existing pre commit hooks that support this. So i'd like to implement one myself. 
Wanted to check to make sure i'm not missing a way to do this currently before i implement.

**Comment by sectioneight** [comment]
cc @sds

**Comment by lencioni** [comment]
I'm not aware of anything. What's your plan?

**Comment by sectioneight** [comment]
Basically for OSS projects there should be a license file in the root. All source files should contain a copy of the license as a comment at the top of the file.

**Comment by sds** [comment]
Implemented in #439. Thanks!
