### ISSUE TITLE
running a git pull --rebase puts me on a remote

### ISSUE THREAD

**Issue by sfahlberg** [brigade/overcommit#446]
I'm not sure whether this is an issue with overcommit or something else. When I do a git pull --rebase on master, it automatically changes my branch to `remotes/origin/HEAD` and it asks for me to `Run 'overcommit --sign' once you've verified the configuration changes.` This is preventing me from updating master

**Comment by jawshooah** [comment]
Could you try again with `OVERCOMMIT_DEBUG=1` and show us all of the output?

**Comment by sfahlberg** [comment]
@jawshooah where do I set that?

**Comment by jawshooah** [comment]
It's just an environment variable. `OVERCOMMIT_DEBUG=1 git pull --rebase`

**Comment by sfahlberg** [comment]
git rev-parse --git-dir
EXIT STATUS: 0
STDOUT: "/Users/sam/directory/.git\n"
STDERR: ""
git config --local --get overcommit.configuration.signature
EXIT STATUS: 0
STDOUT: "26a51f6222d3981283a81c1281a6b302fd5e848fa40cf1400f9256d1a3f80a48\n"
STDERR: ""
git config --local --get overcommit.configuration.signature
EXIT STATUS: 0
STDOUT: "26a51f6222d3981283a81c1281a6b302fd5e848fa40cf1400f9256d1a3f80a48\n"
STDERR: ""
✓ No applicable pre-rebase hooks to run
First, rewinding head to replay your work on top of it...
git rev-parse --git-dir
EXIT STATUS: 0
STDOUT: ".git\n"
STDERR: ""
git config --local --get overcommit.configuration.signature
EXIT STATUS: 0
STDOUT: "26a51f6222d3981283a81c1281a6b302fd5e848fa40cf1400f9256d1a3f80a48\n"
STDERR: ""
git config --local --get overcommit.configuration.signature
EXIT STATUS: 0
STDOUT: "26a51f6222d3981283a81c1281a6b302fd5e848fa40cf1400f9256d1a3f80a48\n"
STDERR: ""
Unable to load configuration from '/Users/sam/directory/.overcommit.yml': Signature of configuration file has changed!
Run `overcommit --sign` once you've verified the configuration changes.
could not detach HEAD

**Comment by jawshooah** [comment]
@sfahlberg This is an unfortunate consequence of how we currently verify hooks and hook configurations, which we plan to improve on: https://github.com/brigade/overcommit/issues/300

For now, you can run `git rebase` or `git pull --rebase` with `OVERCOMMIT_NO_VERIFY=1`.

**Comment by sfahlberg** [comment]
@jawshooah this still doesn't work for me. I get the same error and am returned to remotes/origin/HEAD

**Comment by sds** [comment]
@sfahlberg which version of Overcommit are you running?

**Comment by sfahlberg** [comment]
overcommit 0.36.0

**Comment by jawshooah** [comment]
@sfahlberg Could you run `OVERCOMMIT_DEBUG=1 OVERCOMMIT_NO_VERIFY=1 git pull --rebase`, copy the command and its output and paste it all here?

**Comment by sfahlberg** [comment]
seems like the issue resolved itself. not sure what the issue was. thank you for your help!

**Comment by jawshooah** [comment]
No problem, glad to hear it!
