### ISSUE TITLE
Overcommit shows passing even when ESLint fails to execute correctly

### ISSUE THREAD

**Issue by rbclark** [brigade/overcommit#458]
We were recently having an issue where ESLint was always showing in overcommit as passing on travis even though our version of node was too old and thus ESLint was failing to run (due to the fact that an incompatible version of node came with travis). 

The output of `eslint .` can be seen [here](https://travis-ci.org/projectcypress/cypress/builds/189308181#L532) and the output of overcommit on the same run can be seen [here](https://travis-ci.org/projectcypress/cypress/builds/189308181#L540).

 In cases where ESLint fails to execute correctly, it seems that it would be better to just have ESLint fail other than blindly pass. In this case it meant we were able to merge things into production that were not actually passing our linters.

**Comment by trotzig** [comment]
Good catch. This sounds like a bug to me. Would you be willing to fix this and put together a PR?

**Comment by rbclark** [comment]
I'd be happy to try, let me see what I can put together.
