### ISSUE TITLE
forwarding to private method error raised in 0.37 with Ruby 2.4

### ISSUE THREAD

**Issue by thegranddesign** [brigade/overcommit#464]
My guess is that this is a Ruby 2.4 thing.  I'm starting to get this.

```
/Users/thegranddesign/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/overcommit-0.37.0/lib/overcommit/hook/pre_commit/execute_permissions.rb:27:in `run': Overcommit::Hook::PreCommit::Base#initial_commit? at /Users/thegranddesign/.rbenv/versions/2.4.0/lib/ruby/2.4.0/forwardable.rb:156 forwarding to private method Overcommit::HookContext::PreCommit#initial_commit?
```

**Comment by trotzig** [comment]
Is that a warning or an error?

**Comment by thegranddesign** [comment]
Warning I believe based on the source code changes in 2.4

**Comment by trotzig** [comment]
Looks like this Ruby issue has some context: https://bugs.ruby-lang.org/issues/12782

We might be able to fix this by simply making `initial_commit?` a public method. Here: https://github.com/brigade/overcommit/blob/62132a6996b20e76757a8e4975ef20e89b707b0d/lib/overcommit/hook_context/pre_commit.rb#L174

Want to take a stab at fixing this in a PR?
