### ISSUE TITLE
Add pre-commit hook for license_finder

### ISSUE THREAD

**Issue by rvirani1** [brigade/overcommit#482]
Hi, 

We've recently started using the license_finder gem in our project. It would be great to write a pre-commit hook that would run license finder if any package file (Gemfile.lock, yarn.lock, etc) was changed and then stop if license_finder returned a non-zero exit code. I'd be happy to write a hook if others were interested.

**Comment by trotzig** [comment]
I think this would be a great addition! I'd be happy to review a PR. 

I'm assuming you mean this tool: https://github.com/pivotal/LicenseFinder

**Comment by rvirani1** [comment]
Yes, that's the one. I'll begin working on a PR.
