### ISSUE TITLE
Thanks for the help!

### ISSUE THREAD

**Issue by IanWhitney** [brigade/overcommit#485]
Not an issue, but there's no other way to do these sorts of things in GitHub.

Wanted to let you know that I put up a quick guide to combining Reek and Overcommit

http://designisrefactoring.com/2017/04/05/combining-reek-and-overcommit/

**Comment by sds** [comment]
Great blog post, @IanWhitney!

Do you think it's worthwhile to update Overcommit's [default configuration](https://github.com/brigade/overcommit/blob/fc4e7de9c2098b22a042c03877ec662a60b41ffb/config/default.yml#L490) to include the new `--force-exclusion` flag for the `Reek` pre-commit hook?

If so, would you be will to submit a PR for it? Thanks!

**Comment by trotzig** [comment]
Great! Is this something you think should be in the Reek check by default?

**Comment by IanWhitney** [comment]
I thought about submitting a PR to change the Overcommit hook, but using the new Reek flag requires you be on version >= 4.6.0. People on older versions will get an error.
