### ISSUE TITLE
Should echo commit message when commit is denied

### ISSUE THREAD

**Issue by m-o-e** [brigade/overcommit#494]
Overcommit should echo the user provided commit message to stdout
whenever it declines a commit, so it can be copy/pasted for a new attempt.

Currently all input is lost when a validation fails, which is very frustrating
and discourages users from writing elaborate commit messages.

**Comment by sds** [comment]
I agree this isn't a great experience, @m-o-e.

Perhaps we can leverage Git's [`core.editor`](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#__code_core_editor_code) configuration to re-open the editor you used to write the commit message in the event of a failed hook run.

**Comment by henrahmagix** [comment]
Added a PR in #519

**Comment by henrahmagix** [comment]
@sds I'd love to get some feedback on #519 please =)

**Comment by sds** [comment]
Implemented in #519
