### ISSUE TITLE
README Link for how to create a overcommit precommit hook is dead

### ISSUE THREAD

**Issue by bbugh** [brigade/overcommit#503]
<img width="858" alt="pasted_image_7_27_17__1_33_pm" src="https://user-images.githubusercontent.com/438465/28686268-436e27aa-72d0-11e7-81b3-adbdeb620aa2.png">

The link this points to in the README is dead, unfortunately. Google didn't return any other results for this. [The Wayback Machine has a copy](https://web.archive.org/web/20170312110705/http://www.guoxiang.me/posts/28-how-to-write-a-custom-overcommit-precommit-git-hook-in-4-steps), though.

I wonder if @tgxworld has this uploaded somewhere else? 

If it's out of date, maybe it can be removed.

**Comment by trotzig** [comment]
Cool, let's here if we get a response from @tgxworld. If not, we can just remove the link.

**Comment by sds** [comment]
Removed in 3de81fdcf977d511e9a0ddaa4a311c30aa6b6f87 since we didn't get a response.

Thanks for calling it out!
