### ISSUE TITLE
Reverse word env variable for disabling overcommit

### ISSUE THREAD

**Issue by swelther** [brigade/overcommit#506]
I'm a terrible lazy person. Because of that I can't remember the correct environment variable to disable overcommit when I need it in those rare cases. First I try `DISABLE_OVERCOMMIT=1 git commit` just to notice it was the other way around.

What do you guys think of using the reversed wording `DISABLE_OVERCOMMIT=1` in addition to the normal one? It would really help and such lazy people like me and make them happy :blush: 

Would happily contribute a PR if this idea is somewhat reasonable to you.

**Comment by trotzig** [comment]
I wonder if this would really solve the problem. Would it make sense to instead log something from overcommit when it fails, informing you about how you can ignore certain hooks. Something like 

```
✗ One or more pre-commit hooks failed. 
To ignore failures, add `SKIP=<hook name>` in front of your command. E.g. `SKIP=EsLint git commit`. 
```

(preferring `SKIP` here over disabling overcommit as it's a more lightweight way to disable certain parts of overcommit).

**Comment by swelther** [comment]
Might be an idea. My first thought was that "disable overcommit" makes more sense than the other way around. Just from the speech :)

Normally I have to use it for stashing or WIP/backup commits when I intend to resume the work next day or on another machine and just want to push the branch.

But to be honest, I was not aware of the SKIP variable. Might be the solution for me because it is almost always rubocop that complains (about my binding.pry e.g.). Thanks for the idea :blush:

**Comment by trotzig** [comment]
There's also `SKIP=all` which you can use in the WIP scenario you're describing.

**Comment by swelther** [comment]
`SKIP=all` is just awesome! And so much easier to remember. Thanks, everything I need :blush:
