### ISSUE TITLE
Optionally disable colorized output

### ISSUE THREAD

**Issue by harto** [brigade/overcommit#508]
Would it be possible to always disable colorization of log output?
I'm running into the issue described here: https://groups.google.com/forum/#!topic/magit/oMNrMUvxTTs

It seems like `Overcommit::Logger#color` could additionally read some configuration option (environment variable?) and decide whether to include the ANSI escape sequences or not.

Would you accept a PR along those lines?

**Comment by sds** [comment]
Hey @harto, thanks for opening an issue.

Would happily accept a pull request adding support for enabling/disabling of color via an environment variable. I would think `OVERCOMMIT_COLOR` should suffice, here. Thanks!
