### ISSUE TITLE
LineEndings pre-commit hook crashes when passed filenames with spaces

### ISSUE THREAD

**Issue by okeefm** [brigade/overcommit#512]
Running the `LineEndings` pre-commit task in Overcommit crashes with the following error when run against a codebase with files with spaces in the names:

```Hook raised unexpected error
uncaught throw #<Errno::ENOENT: No such file or directory @ rb_sysopen - resources/schematron/cat1/2016/HQR>
~/.rvm/gems/ruby-2.3.4/gems/overcommit-0.41.0/lib/overcommit/hook/pre_commit/line_endings.rb:17:in `throw'
~/.rvm/gems/ruby-2.3.4/gems/overcommit-0.41.0/lib/overcommit/hook/pre_commit/line_endings.rb:17:in `rescue in block in run'
~/.rvm/gems/ruby-2.3.4/gems/overcommit-0.41.0/lib/overcommit/hook/pre_commit/line_endings.rb:12:in `block in run'
~/.rvm/gems/ruby-2.3.4/gems/overcommit-0.41.0/lib/overcommit/hook/pre_commit/line_endings.rb:9:in `map'
~/.rvm/gems/ruby-2.3.4/gems/overcommit-0.41.0/lib/overcommit/hook/pre_commit/line_endings.rb:9:in `run'
~/.rvm/gems/ruby-2.3.4/gems/overcommit-0.41.0/lib/overcommit/hook/base.rb:45:in `block in run_and_transform'
~/.rvm/gems/ruby-2.3.4/gems/overcommit-0.41.0/lib/overcommit/utils.rb:260:in `with_environment'
~/.rvm/gems/ruby-2.3.4/gems/overcommit-0.41.0/lib/overcommit/hook/base.rb:45:in `run_and_transform'
~/.rvm/gems/ruby-2.3.4/gems/overcommit-0.41.0/lib/overcommit/hook_runner.rb:155:in `run_hook'
~/.rvm/gems/ruby-2.3.4/gems/overcommit-0.41.0/lib/overcommit/hook_runner.rb:88:in `block in consume'
~/.rvm/gems/ruby-2.3.4/gems/overcommit-0.41.0/lib/overcommit/hook_runner.rb:85:in `loop'
~/.rvm/gems/ruby-2.3.4/gems/overcommit-0.41.0/lib/overcommit/hook_runner.rb:85:in `consume'
```

The full file path of the file that causes the error is `resources/schematron/cat1/2016/HQR CMS QRDA Category I.sch`. 

I'm running Overcommit version `0.41.0` in Ruby `2.3.4`, on Mac OS X `10.12.6`, using Git version `2.11.0`. 

The issue seems to be occurring here: https://github.com/brigade/overcommit/blob/master/lib/overcommit/hook/pre_commit/line_endings.rb#L56, when the code splits the `git ls-files` result on spaces. The change that needs to be made, most likely, is changing that line to `i, _w, _attr, path = file_info.split(' ', 4)`. The addition of the `4` argument will cause the function to return at most 4 splits, adding the rest of what would have been split into the `path` variable, which is the desired effect.

**Comment by sds** [comment]
Thanks for the report, @okeefm. Fixed in 3032812746e190de8dc0555c6d5b1e389aa6eabc
