### ISSUE TITLE
Pre-Push: TestUnit

### ISSUE THREAD

**Issue by benjamin852** [brigade/overcommit#513]
Hi Everyone.

I am trying to implement the TestUnit hook to ensure that all my tests in my app run before I commit. What I did so far to enable the TestUnit was I changed the TestUnit: enabled to true in the default.yml file.
<img width="664" alt="screen shot 2017-09-27 at 5 18 39 pm" src="https://user-images.githubusercontent.com/13651771/30918863-7457621a-a3a8-11e7-8748-48115ae54a35.png">
 So now when I run overcommit -l it shows that the TestUnit is enabled.
<img width="135" alt="screen shot 2017-09-27 at 5 15 47 pm" src="https://user-images.githubusercontent.com/13651771/30918844-67443288-a3a8-11e7-9194-9f72f30f0d57.png">

Unfortunately when I push my project to Github the push still works even though my tests don't pass, so I have either missed a step or done something wrong. Hoping someone could let me know how I could get this to work.
Thank You!

**Comment by sds** [comment]
Hey @benjamin852,

I don't use `Test::Unit`, but I imagine depending on how you have it set up this hook might not work for you. Hard to tell what's wrong here without additional information. What happens if you run the command the hook _would_ have ran in your repository?

```bash
ruby -Ilib:test -rtest/unit -e 'exit! Test::Unit::AutoRunner.run'"
```

Does this work? My suggestion is to ensure you are running a command that actually runs tests. The hook should pass only if the command returns a zero exit status, as you can see [here](https://github.com/brigade/overcommit/blob/v0.41.0/lib/overcommit/hook/pre_push/test_unit.rb#L8).

**Comment by benjamin852** [comment]
Thanks for responding @sds !

Just for some more details. In my overcommit.yml file (in the root of my project) I have: 
<img width="349" alt="screen shot 2017-10-01 at 11 20 14 am" src="https://user-images.githubusercontent.com/13651771/31052987-fba66d84-a69a-11e7-8eee-19de2d812c55.png">

When I push my file the project push's just fine 
<img width="526" alt="screen shot 2017-10-01 at 11 19 52 am" src="https://user-images.githubusercontent.com/13651771/31052991-0b3e81a0-a69b-11e7-8210-92365dd1e0c2.png">

This is an issue because I deliberately wrote broken a unit test to see if the hook works, but the hook is not catching the broken unit test, in other words the hook should be failing and I am not sure why it is passing.

**Comment by sds** [comment]
Hey @benjamin852, in your first message you mentioned `Test::Unit` but now you're mentioning RSpec. These are two different test frameworks, so I just want to be clear what you're trying to do.

Assuming you're now trying to get this to work with the `RSpec` pre-push hook: does running `rake PracticeOvercommit` return a non-zero exit status?

**Comment by benjamin852** [comment]
@sds sorry about that my bad. I have changed that since I posted the message this morning my code now contains this in the .overcommit.yml
<img width="535" alt="screen shot 2017-10-01 at 3 20 32 pm" src="https://user-images.githubusercontent.com/13651771/31057254-768b4dd8-a6e8-11e7-882e-7f03f34c539a.png">

And my issue now remains with the push working even though my test is still
<img width="510" alt="screen shot 2017-10-01 at 3 20 47 pm" src="https://user-images.githubusercontent.com/13651771/31057268-a430e716-a6e8-11e7-8690-ff972f45ddcb.png">
 broken

sorry about that

**Comment by benjamin852** [comment]
@sds sorry about that my bad. I have changed that since this morning so my code now contains the Test:Unit rather than then RSpec
Here is my .overcommit.yml file 
<img width="535" alt="screen shot 2017-10-01 at 3 20 32 pm" src="https://user-images.githubusercontent.com/13651771/31057333-d7885350-a6e9-11e7-8545-a944ccceeda7.png">

My terminal output remains:
<img width="510" alt="screen shot 2017-10-01 at 3 20 47 pm" src="https://user-images.githubusercontent.com/13651771/31057339-e64038d6-a6e9-11e7-9f2b-1a8bddbcbcec.png">

So I still have the same issue being that my project is successfully pushing even though my unit test is broken. 
Thanks again!

**Comment by nicolaiskogheim** [comment]
@benjamin852 There's still one question you haven't answered yet, and that is what your command returns when you run them directly in your terminal.

What is the output of running the following

1. When all tests pass, and
2. When at least one test fails

```sh
$ rake PracticeOvercommitTests/PracticeOvercommitTests.m
$ echo $?
```
