### ISSUE TITLE
Support for StyleLint in Pre-Commit Hook. 

### ISSUE THREAD

**Issue by brianbancroft** [brigade/overcommit#514]
Hi everyone and thanks for making such a nice tool. I was recently introduced to this and I've since used it in its basic config with Rubocop and ESLint. 

There is a tool I'd love to see integrated called [StyleLint](https://github.com/stylelint/stylelint), which is used where I work, and I'd love to see it integrated into Overcommit. 

A question: If I was to attempt to build something similar to [this](https://github.com/brigade/overcommit/blob/master/lib/overcommit/hook/pre_commit/css_lint.rb) over the next few days, what are the considerations I need to take into mind?

**Comment by sds** [comment]
Hey @brianbancroft,

It should be pretty simple to integrate with another static analysis tool like `StyleLint`. You can see an example of another pull request adding support for a linter here: #437. Happy to accept a pull request!

**Comment by siim2812** [comment]
Hi @brianbancroft,
Are you going do this PR? If you aren't I am going to do this.

**Comment by brianbancroft** [comment]
Hi Slim, 

I was able to get it working this weekend, but I need a bit of help getting across the finish line as far as testing goes. This was my first attempt at doing anything with a gem, so there was a bit I had to grok in addition to my other duties. 

If you want to take it further, feel free. The PR should be coming up in the timeline below V

**Comment by siim2812** [comment]
What is the status of this PR?

**Comment by sds** [comment]
Happy to merge once the comments on #521 are addressed. Thanks!

**Comment by Ruffeng** [comment]
hi @sds, @brianbancroft. I wanted to help with this issue. Seems that it's been in standby for a while, so I decided to check what we can do to make it work and add these tests. 

I've found an issue regarding the format of stylelint, seems the regular output is:

```
build/main-83c1d3ccb36daab8.css
5:1  ⚠ 'Expected ".foo.bar" to have specificity no more than "0,1,0"

41:6  ⚠ 'Expected ".foo.bar" to have specificity no more than "0,1,0"
```
I am not sure if Overcommit is prepared to handle an output that shows just once the name of the file and then goes by lines for that file. Checking the base.rb from the hooks seems it's all time waiting for the regex `<file>,<line>,<type>`, and this output it's not providing these requirements.

If there is a way to do it, please let me know and I can work on it if you want.
On the other hand, I am going to open an issue in stylelint, asking for supporting the kind of output that Overcommit could work on that.

I'll reply back when I get any kind of new from their side 👍

**Comment by sds** [comment]
Added in #590
