### ISSUE TITLE
Ad-hoc hook subclassing

### ISSUE THREAD

**Issue by tilgovi** [brigade/overcommit#535]
I'm finding Overcommit to be a bit difficult in a repository containing multiple Python projects. Some projects are Python 2 while others are Python 3 and each has its own virtual environment. Since Overcommit uses the hook class name as the configuration key it's not possible to run a single kind of hook multiple times with different invocations / configurations.

Having spent some time with this problem and locally created a multi-hook plugin to work around the issue, I think I've identified a way to solve it upstream.

Would you consider a PR that adds support for a `base` or `class` (without loss of generality) key on ad-hoc hooks that lets ad-hoc hooks derive from an existing class? I believe that would make it possible to dynamically create new hook classes that inherit existing functionality without breaking the API contract of `Overcommit::Hook::Base.initialize` and the 1:1 association between configuration blocks and hook classes.

**Comment by sds** [comment]
Hey @tilgovi,

This has been [discussed](https://github.com/brigade/overcommit/issues/139#issuecomment-85255956) in the past (specifically adding an `inherit` option, similar to your suggestion of `base` or `class`).

I'm open to a pull request but would want to see serious thought given to how configuration is inherited, especially in subclasses of subclasses, and whether inheritance includes configuration options or just the implementation of the hook itself.

**Comment by tilgovi** [comment]
I would not add the complexity of combining multiple configuration files. I would only want to support allowing ad hoc plugins to inherit from an existing class (probably inheriting it's defaults, too). That would allow a single `.overcommit.yml` to run a checker multiple times with different options.

**Comment by tilgovi** [comment]
I'll see if I can hack something together. If so, I'll open a PR. You've answered my question, though. Thanks!
