### ISSUE TITLE
"Directory not empty" error after upgrading 0.41 → 0.42: 

### ISSUE THREAD

**Issue by mattbrictson** [brigade/overcommit#554]
After upgrading overcommit from 0.41.0 to 0.42.0, the first time I attempt to use `git commit` on an overcommit-enabled project I get this crash:

```
$ git commit
Directory not empty @ dir_s_rmdir - /Users/mbrictson/Code/myapp/.git/hooks/old-hooks
/Users/mbrictson/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:250:in `rmdir'
/Users/mbrictson/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:250:in `block in rmdir'
/Users/mbrictson/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:249:in `each'
/Users/mbrictson/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:249:in `rmdir'
/Users/mbrictson/Code/overcommit/lib/overcommit/installer.rb:142:in `preserve_old_hooks'
/Users/mbrictson/Code/overcommit/lib/overcommit/installer.rb:58:in `update'
/Users/mbrictson/Code/overcommit/lib/overcommit/installer.rb:20:in `run'
.git/hooks/pre-commit:67:in `<main>'
Report this bug at https://github.com/brigade/overcommit/issues
```

Digging in a bit further, I found that 3c37254 in 0.42.0 made a trivial change to the git hooks. Thus, the first time overcommit 0.42 is used on a existing overcommit-enabled project, it will attempt to upgrade to the new version of the git hooks.

It backs up any existing hooks to `old_hooks_path`, and then reaches this line:

```ruby
# Remove old-hooks directory if empty
FileUtils.rmdir(old_hooks_path)
```

For me, this fails with a "Directory not empty" error. Seems like there should be a guard clause here that skips the `rmdir` if the directory is not empty?

https://github.com/brigade/overcommit/blob/838a571852ac43e782dba58264f542c9a8a9d913/lib/overcommit/installer.rb#L129-L143

**Comment by sds** [comment]
Hey @mattbrictson, thanks for discovering this. This is really weird, as our tests should have picked this up.

Running the tests on my local Mac, I found that they did indeed fail. This tells me that there is some sort of platform difference between TravisCI and macOS which I don't have bandwidth to dig into right now. What's more frustrating is that there's not an easy way to tell when the breakage started (this code is pretty old, which suggests to me this issue started happening recently).

Thanks again for the report!

**Comment by monfresh** [comment]
The fix in https://github.com/brigade/overcommit/commit/7c85c6651b7249cecf92f2cfa848bbd16a488f03 doesn't seem to work for me. I'm on macOS 10.12.6 with Ruby 2.5.0. I updated my Gemfile to point to the master branch of overcommit, and when I run `overcommit --install`, it still fails. It looks like it's trying to move the hooks into my home folder, not the current project's directory:

```
Installing hooks into /Users/monfresh/projects/my_app
Hook '/Users/monfresh/projects/my_app/pre-commit' already exists and was not installed by Overcommit. Moving to '/Users/monfresh/.git-support/hooks/old-hooks'
Traceback (most recent call last):
  13: from /Users/monfresh/.gem/ruby/2.5.0/bin/overcommit:23:in `<main>'
  12: from /Users/monfresh/.gem/ruby/2.5.0/bin/overcommit:23:in `load'
  11: from /Users/monfresh/.gem/ruby/2.5.0/gems/overcommit-0.42.0/bin/overcommit:49:in `<top (required)>'
  10: from /Users/monfresh/.gem/ruby/2.5.0/gems/overcommit-0.42.0/lib/overcommit/cli.rb:24:in `run'
   9: from /Users/monfresh/.gem/ruby/2.5.0/gems/overcommit-0.42.0/lib/overcommit/cli.rb:125:in `install_or_uninstall'
   8: from /Users/monfresh/.gem/ruby/2.5.0/gems/overcommit-0.42.0/lib/overcommit/cli.rb:125:in `each'
   7: from /Users/monfresh/.gem/ruby/2.5.0/gems/overcommit-0.42.0/lib/overcommit/cli.rb:127:in `block in install_or_uninstall'
   6: from /Users/monfresh/.gem/ruby/2.5.0/gems/overcommit-0.42.0/lib/overcommit/installer.rb:22:in `run'
   5: from /Users/monfresh/.gem/ruby/2.5.0/gems/overcommit-0.42.0/lib/overcommit/installer.rb:34:in `install'
   4: from /Users/monfresh/.gem/ruby/2.5.0/gems/overcommit-0.42.0/lib/overcommit/installer.rb:142:in `preserve_old_hooks'
   3: from /Users/monfresh/.rubies/ruby-2.5.0/lib/ruby/2.5.0/fileutils.rb:249:in `rmdir'
   2: from /Users/monfresh/.rubies/ruby-2.5.0/lib/ruby/2.5.0/fileutils.rb:249:in `each'
   1: from /Users/monfresh/.rubies/ruby-2.5.0/lib/ruby/2.5.0/fileutils.rb:250:in `block in rmdir'
/Users/monfresh/.rubies/ruby-2.5.0/lib/ruby/2.5.0/fileutils.rb:250:in `rmdir': Directory not empty @ dir_s_rmdir - /Users/monfresh/.git-support/hooks/old-hooks (Errno::ENOTEMPTY)
command failed (pid 36350 exit 1): overcommit --install
```

**Comment by monfresh** [comment]
I figured it out. I had to run `bundle exec overcommit --install`. For some reason, it was not using the correct version of the gem without the `bundle exec`.

**Comment by sds** [comment]
Thanks for following up, @monfresh. The behavior your observed seems surprising, as Overcommit should automatically respect the Bundler context defined by the `gemfile` option in your `.overcommit.yml`: https://github.com/brigade/overcommit/blob/master/bin/overcommit#L5-L31
