### ISSUE TITLE
Add pre-commit validation for Dockerfiles

### ISSUE THREAD

**Issue by rbanffy** [brigade/overcommit#556]
Overcommit doesn't have an option to validate Dockerfile files. I'd love to implement that.

**Comment by sds** [comment]
Hey @rbanffy, please see the [hadolint](https://github.com/brigade/overcommit/blob/master/lib/overcommit/hook/pre_commit/hadolint.rb) pre-commit hook, which has existed since version 0.40.0. Thanks!
