### ISSUE TITLE
Post-checkout failure

### ISSUE THREAD

**Issue by mvz** [brigade/overcommit#560]
This just happened, I'm not sure what's going on:

```
± [matijs@bean master+] git co -b rails-5-2
Switched to a new branch 'rails-5-2'
Directory not empty @ dir_s_rmdir - /home/matijs/Projects/playdate/.git/hooks/old-hooks
/home/matijs/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:250:in `rmdir'
/home/matijs/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:250:in `block in rmdir'
/home/matijs/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:249:in `each'
/home/matijs/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:249:in `rmdir'
/home/matijs/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/overcommit-0.43.0/lib/overcommit/installer.rb:142:in `preserve_old_hooks'
/home/matijs/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/overcommit-0.43.0/lib/overcommit/installer.rb:58:in `update'
/home/matijs/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/overcommit-0.43.0/lib/overcommit/installer.rb:20:in `run'
.git/hooks/post-checkout:67:in `<main>'
Report this bug at https://github.com/brigade/overcommit/issues
```

I *think* overcommit made `old-hooks` in the first place, so it shouldn't be surprised to find stuff there.

Update: This happens on regular branch checkout as well.

**Comment by sds** [comment]
Hey @mvz, this issue should have been fixed by 7c85c6651b7249cecf92f2cfa848bbd16a488f03 (reported in #554).

Would really appreciate if you temporarily modified `lib/overcommit/installer.rb:142` to add `Dir.entries(old_hooks_path).inspect` before that line on your system. Thanks!

**Comment by mvz** [comment]
Hi @sds, the result of that puts is:

```
[".", "..", "commit-msg", "pre-rebase", "pre-commit", "post-commit"]
```

**Comment by sds** [comment]
Apologies @mvz. I thought we had released the fix already.

Please update to Overcommit [0.44.0](https://github.com/brigade/overcommit/releases/tag/v0.44.0) to avoid this issue. Thanks!
