### ISSUE TITLE
With overcommit enabled, git submodule commits cause "fatal: Path '.gitmodules' exists on disk, but not in 'HEAD'."

### ISSUE THREAD

**Issue by GreatBigBore** [brigade/overcommit#562]
git version 2.16.2, overcommit 0.43.0

# Steps to reproduce:
1. Create folder, go into folder, git init
2. Add a file, git commit
3. git submodule add https://github.com/JohnEstropia/CoreStore.git
4. git status shows .gitmodules and CoreStore ready to be committed
5. git commit

# Observed Behavior
1. overcommit says a couple of innocuous things
2. git says `fatal: Path '.gitmodules' exists on disk, but not in 'HEAD'.`
3. overcommit moves along like nothing happened
4. it looks like the commit went ok. See below.

# Expected Behavior
The following, minus the debug info and the fatal error message

# Commit with overcommit debug turned on

    :> OVERCOMMIT_DEBUG=1 git commit -m "Trying CoreStore again"
    git rev-parse --git-dir
    EXIT STATUS: 0
    STDOUT: ".git\n"
    STDERR: ""
    git config --local --get overcommit.configuration.signature
    EXIT STATUS: 0
    STDOUT: "b24059ab7d3bc4223f3eaa4e848ccbbafebc322f6c303c4abad4556c7805c1f2\n"
    STDERR: ""
    git config --local --get overcommit.configuration.signature
    EXIT STATUS: 0
    STDOUT: "b24059ab7d3bc4223f3eaa4e848ccbbafebc322f6c303c4abad4556c7805c1f2\n"
    STDERR: ""
    git rev-parse HEAD
    EXIT STATUS: 0
    STDOUT: "04b37fe72b7999f9ca47f96670a06ca47321a870\n"
    STDERR: ""
    git -c commit.gpgsign=false stash save --keep-index --quiet Overcommit: Stash of repo state before hook run at 2018-02-26 20:02:45 -0800
    EXIT STATUS: 0
    STDOUT: ""
    STDERR: "warning: unable to rmdir 'CoreStore': Directory not empty\n"
    Running pre-commit hooks
    git rev-parse HEAD
    grep -IHn ^<<<<<<<[ ] ... (1 splittable args)
    EXIT STATUS: 0
    STDOUT: "04b37fe72b7999f9ca47f96670a06ca47321a870\n"
    STDERR: ""
    EXIT STATUS: 1
    STDOUT: ""
    STDERR: ""

    ✓ All pre-commit hooks passed

    fatal: Path '.gitmodules' exists on disk, but not in 'HEAD'.
    git reset --hard
    EXIT STATUS: 0
    STDOUT: "HEAD is now at 04b37fe Initial\n"
    STDERR: "warning: unable to rmdir 'CoreStore': Directory not empty\n"
    git stash pop --index --quiet
    EXIT STATUS: 0
    STDOUT: ""
    STDERR: ""
    git rev-parse --git-dir
    EXIT STATUS: 0
    STDOUT: ".git\n"
    STDERR: ""
    git config --local --get overcommit.configuration.signature
    EXIT STATUS: 0
    STDOUT: "b24059ab7d3bc4223f3eaa4e848ccbbafebc322f6c303c4abad4556c7805c1f2\n"
    STDERR: ""
    git config --local --get overcommit.configuration.signature
    EXIT STATUS: 0
    STDOUT: "b24059ab7d3bc4223f3eaa4e848ccbbafebc322f6c303c4abad4556c7805c1f2\n"
    STDERR: ""
    Running commit-msg hooks
    Check for trailing periods in subject................[TrailingPeriod] OK
    Check text width..........................................[TextWidth] OK
    Check subject capitalization.....................[CapitalizedSubject] OK
    Check subject line................................[SingleLineSubject] OK

    ✓ All commit-msg hooks passed

    git rev-parse --git-dir
    EXIT STATUS: 0
    STDOUT: ".git\n"
    STDERR: ""
    git config --local --get overcommit.configuration.signature
    EXIT STATUS: 0
    STDOUT: "b24059ab7d3bc4223f3eaa4e848ccbbafebc322f6c303c4abad4556c7805c1f2\n"
    STDERR: ""
    git config --local --get overcommit.configuration.signature
    EXIT STATUS: 0
    STDOUT: "b24059ab7d3bc4223f3eaa4e848ccbbafebc322f6c303c4abad4556c7805c1f2\n"
    STDERR: ""
    ✓ No applicable post-commit hooks to run
    [master abd78c1] Trying CoreStore again
    2 files changed, 4 insertions(+)
    create mode 100644 .gitmodules
    create mode 160000 CoreStore

# Workaround
`OVERCOMMIT_DISABLE=1 commit...`
I can't tell whether this actually gets around the problem, or just covers up a deeper problem.

## .overcommit.yml
    CommitMsg:      
      TextWidth:
        enabled: true
        on_warn: fail

**Comment by sds** [comment]
Thanks for the report, @GreatBigBore!
