### ISSUE TITLE
A Terraform formatter on pre-commit would be useful

### ISSUE THREAD

**Issue by rbanffy** [brigade/overcommit#567]
Frequently we see terraform .tf/tfvars files with diverging formats. Running `terraform fmt` on pre-commit would be awesome.

BTW, if I submit a plugin for this, would it be considered?

**Comment by rbanffy** [comment]
If I submit a plugin for this, would it be considered?

**Comment by sds** [comment]
Happy to merge a pull request!

**Comment by rbanffy** [comment]
I have a couple other ideas and two weeks of vacation ahead of me. :-)
