### ISSUE TITLE
StringMatcher?

### ISSUE THREAD

**Issue by nbarnes** [brigade/overcommit#573]
A pre-commit hook for catching string matches within changed files would be fantastic for catching overlooked debugging statements (I can't be the only person with commit subjects reading 'Removed binding.pry').  Call it StringMatcher?

**Comment by sds** [comment]
Hey @nbarnes, this is a pretty simple hook to implement yourself. A generic implementation wouldn't provide that much additional value, as what's important about these "forbidden strings" are that when you warn on them you provide a helpful message explaining to developers why the presence of that string is a problem. 

You can see a simple example of such a hook with the [MergeConflicts pre-commit hook](https://github.com/brigade/overcommit/blob/master/lib/overcommit/hook/pre_commit/merge_conflicts.rb) and its [corresponding configuration](https://github.com/brigade/overcommit/blob/6194c334e0c64618428c6abc626c67b2a450de28/config/default.yml#L451-L456).

Furthermore, a nice feature of Overcommit is being able to skip hooks by name. If you're adding multiple blacklisted strings to a single `StringMatcher` hook, you don't have that benefit, and could accidentally skip all checks for forbidden strings by doing so.

Hope that explains the rationale here. Strongly recommend you create your own hooks for forbidden strings!
