### ISSUE TITLE
Command not executed

### ISSUE THREAD

**Issue by damien-biasotto** [brigade/overcommit#579]
So first of all, very nice tool :)

This issue is regarding an upcoming PR, I'm trying to create a hook for PHP-Cs-Fixer : 

Before I submit that pull-request, I tried it on one of my project. Somehow the hook says  everything is fine, but the file was not touched.

If I run the same command manually, the file is updated. I'm not sure how to debug that (I'm brand new in the ruby world). and what I'm doing wrong  and I could use your help.

**Comment by sds** [comment]
Hey @damien-biasotto, glad you're finding value with the tool.

Overcommit does not yet support pre-commit hooks with file-changing side effects. See #238 for details. Hope that explains what you're observing!

**Comment by damien-biasotto** [comment]
Ah indeed that makes  sense :)
