### ISSUE TITLE
How can we use a tab character in a spec file?

### ISSUE THREAD

**Issue by craig-davis** [brigade/overcommit#608]
## Problem
The `HardTabs` pre-commit hook prevents spec files from having hard tabs in example output used to test parsing.

## Background
I'm preparing [a new PR that introduces support](https://github.com/brigade/overcommit/compare/master...craig-davis:pre-commit-phpmd?expand=1) for [PHP Mess Detector](https://phpmd.org/), and the spec test for parsing the output of the command includes hard tabs. The spec file I'm working with looks like this with the tabs highlighted.

![screenshot](http://c.hlp.sc/b4885863ed0d/Image%2525202018-11-01%252520at%2525209.12.51%252520PM.png)

## Question
What's the best approach to including this tabbed example output in a spec file?

**Comment by sds** [comment]
Hey @craig-davis, anything holding you back from using the `\t` escape sequence to represent a tab? 

Just switch from single quotes to double quotes in your strings and replace a literal tab with `\t`. Hope that helps!
