### ISSUE TITLE
Overcommit relies on unmaintained/broken childprocess gem

### ISSUE THREAD

**Issue by Br3nda** [brigade/overcommit#610]
Installing on ruby 2.6.0 no longer works because:
```
The internal error was:
	(NoMethodError) undefined method `[]' for nil:NilClass
ERROR:  While executing gem ... (NoMethodError)
    undefined method `[]' for nil:NilClass
```
I traced this to installing the childprocess gem. It has been in maintenance mode for a while, and from about March 2018 unmaintained.
https://github.com/enkessler/childprocess/issues/131

It looks like it's time to depend on a different gem.

**Comment by sds** [comment]
Hey @Br3nda, thanks for opening an issue. When I `gem install overcommit` on Ruby 2.6.0 I don't get any such error. Nor do I get that when I `gem install childprocess` explicitly.

Can you clarify what you're doing to see that error? Also, can you confirm the output of:

```
ruby --version
```
```
gem --version
```
```
bundler --version
```

For context, on my system I get:
```
⨠ ruby --version
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
⨠ gem --version
3.0.1
⨠ bundler --version
Bundler version 1.17.3
```

**Comment by Br3nda** [comment]
Maybe this will help reproduce it:

```
$ gem install childprocess
```

This results in:
```
Successfully installed childprocess-0.9.0
Parsing documentation for childprocess-0.9.0
Before reporting this, could you check that the file you're documenting
has proper syntax:

  /home/brenda/.rbenv/versions/2.6.0/bin/ruby -c lib/childprocess/tools/generator.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

	(NoMethodError) undefined method `[]' for nil:NilClass

ERROR:  While executing gem ... (NoMethodError)
    undefined method `[]' for nil:NilClass
```

**Comment by sds** [comment]
What happens if you run `gem install childprocess --no-document`?

**Comment by sds** [comment]
FWIW, this appears to be a problem with RDoc.

Ruby 2.5.3 installs RDoc *6.0.1*. Ruby 2.6.0 installs RDoc *6.1.0*.

If you install RDoc 6.1.0 on Ruby 2.5.3 and run `gem install childprocess --document`, you'll get the same error. Thus I would blame this problem on RDoc and not `childprocess`, as it appears to be choking on the [heredoc](https://github.com/enkessler/childprocess/blob/v0.9.0/lib/childprocess/tools/generator.rb#L49) in one of the childprocess Ruby files.

A workaround in the childprocess gem might be to add [`:stopdoc:` / `:startdoc:`](https://ruby.github.io/rdoc/RDoc/Markup.html#class-RDoc::Markup-label-Controlling+what+is+documented) directives to the problematic file ([`lib/childprocess/tools/generator.rb`](https://github.com/enkessler/childprocess/blob/v0.9.0/lib/childprocess/tools/generator.rb) in this case).

It looks like other projects have had to implement this workaround in the past, e.g. [Puppet](https://github.com/jes5199/puppet/commit/5c05cfab09058dd748159fb08ac1e533fecda8e9).

The easier workaround would be to disable RDoc installation by addnig the `--no-document` flag to your `gem install` commands (or disable it globally in your `~/.gemrc` file).

I'm going to close this as the problem as originally stated seems to be unrelated. I've offered to the current maintainer to [take over maintenance for `childprocess`](https://github.com/enkessler/childprocess/issues/131#issuecomment-451226312). We'll see what they say.

**Comment by Br3nda** [comment]
Thank you!
That worked.
